$axure.loadCurrentPage({
  "url":"_donation_instructions.html",
  "generationDate":new Date(1426468452505.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4feea4bae5ce4db2961f469ab2667a29",
    "type":"Axure:Page",
    "name":"!Donation Instructions",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8d1eb8e4fd58486580956464f1be7d76",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"3c2651543160467bb6dbd1c6e4fb5ae6"},
{
          "id":"9be071765d1444d4bc3647c3f5e59185",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":31,
              "y":459.999969482422},
            "size":{
              "width":426,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c8b250dcfc144a4b591a359a02b0b3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":31,
                  "y":459.999969482422},
                "size":{
                  "width":426,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6864a621d8134e0093117dab22d3d578",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":31,
              "y":511.999969482422},
            "size":{
              "width":539,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c7d83ee9a3e436aaaec801e8da00d2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":31,
                  "y":511.999969482422},
                "size":{
                  "width":539,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb58455cc8d24a0e828128a5a6230c5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":31,
              "y":717},
            "size":{
              "width":410,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"424ff4114d4843fab026724b461880d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":31,
                  "y":717},
                "size":{
                  "width":410,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a43f0fbd80e4c4990914bc78c22532b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":31,
              "y":790},
            "size":{
              "width":499,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2576311dd57b4f72b26ad7de5faf07c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":31,
                  "y":790},
                "size":{
                  "width":499,
                  "height":360}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0fe002df9ae4cf8bbd3beff490dafdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":31,
              "y":760},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea4f3a12ccba4206828da3438d7c8935",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":31,
                  "y":760},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c0206cc196349b4a2fdd4e48855976e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":610,
              "y":790},
            "size":{
              "width":499,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4999b67d7aa48bbbf962929b119ba65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":610,
                  "y":790},
                "size":{
                  "width":499,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e0b9c83f9cd457883417949458d2761",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":610,
              "y":760},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5410eff50dc545609aa96e02c76d6ab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":610,
                  "y":760},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c3047f77deb4af4a933fa922c36fa62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":31,
              "y":227},
            "size":{
              "width":395,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7ea4a932d7442639c343bc7b3e5be78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":31,
                  "y":227},
                "size":{
                  "width":395,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea63b3a425b94270a4af689c60d90616",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":31,
              "y":281},
            "size":{
              "width":512,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"073cb1ddce5f41069d2addc752e5b8e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":31,
                  "y":281},
                "size":{
                  "width":512,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffcf6beeb0044cabbeedd988c17ab00e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":31,
              "y":632},
            "size":{
              "width":509,
              "height":42}},
          "adaptiveStyles":{
}},
{
          "id":"49a6da6f1a7447d1a117f11dc6726dc1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":31,
              "y":363},
            "size":{
              "width":509,
              "height":42}},
          "adaptiveStyles":{
}},
{
          "id":"5c16768c64f847e4b14e19c20490eb44",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":31,
              "y":1160},
            "size":{
              "width":509,
              "height":42}},
          "adaptiveStyles":{
}},
{
          "id":"84e2bf8d40d2424aae781d0430d74f11",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":610,
              "y":1160},
            "size":{
              "width":509,
              "height":42}},
          "adaptiveStyles":{
}},
{
          "id":"98c6ad4fd61d4dc885bae17eed65c27b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1250}},
          "adaptiveStyles":{
},
          "masterId":"1c043ff96f1947a9b4613e78a73b6b0b"}]}},
  "masters":{
    "3c2651543160467bb6dbd1c6e4fb5ae6":{
      "packageId":"3c2651543160467bb6dbd1c6e4fb5ae6",
      "type":"Axure:Master",
      "name":"Хидер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a24d26dd8cbf4f848f51c061f19d3ec2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-30},
              "size":{
                "width":1280,
                "height":207}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad4a5933465143999cd6214d999692d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-30},
                  "size":{
                    "width":1280,
                    "height":207}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.png"}},
{
            "id":"1986c1faae294ce5b785ebea9c9954d1",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":109},
              "size":{
                "width":1280,
                "height":68}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b476c7edf27f4f47a1e333f7f8061d5e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":1280,
                    "height":68}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2008e102df584d74a483975847661c17",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"824e543911104969870ab12502c80eda",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u5.png"}},
{
                    "id":"b51e264b43464b27af113cbf070b274d",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":183,
                        "y":0},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0e31ad92b7bc4eeb941d4fc5633165db",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":183,
                            "y":0},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open !All Projects in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"_all_projects.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u5.png"}},
{
                    "id":"94faf73cf2a140e1b5a65136362028b0",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":366,
                        "y":0},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"24f6277a43d84fe58c2bcc94f1624738",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":366,
                            "y":0},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open !Buisness in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"_buisness.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u5.png"}},
{
                    "id":"41195ca2d4eb4b25b02f328962a88fea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":549,
                        "y":0},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"262376ede03e425c805a7ee916d5dc4d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":549,
                            "y":0},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open !Diaspora in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"_diaspora.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u5.png"}},
{
                    "id":"774d22def07f4b3b92beaf7d3113c8e3",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":732,
                        "y":0},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f3ade7596611440d93de5a3f4d363b75",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":732,
                            "y":0},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u5.png"}},
{
                    "id":"24db02bcbff8461cbea21ec682c852e4",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":1098,
                        "y":0},
                      "size":{
                        "width":182,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c477273f7bd4c68b1992c1e467819a1",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":1098,
                            "y":0},
                          "size":{
                            "width":182,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open !About in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"_about.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u17.png"}},
{
                    "id":"9bba04f51c5e482eab48c197c0c5363f",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":915,
                        "y":0},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"782008b02e71410c967b33d141b84e61",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":915,
                            "y":0},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open !News in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"_news.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u5.png"}}]},
{
                "id":"9ac348a26857416bb79680212145b5ee",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":732,
                    "y":68},
                  "size":{
                    "width":183,
                    "height":184},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"57f74f87cb2b4977906ae56b1eff6a24",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":183,
                        "height":184}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aa6e42cab61645a796d2e7097ab11d74",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":183,
                            "height":52},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"77b18f4acbcf48d1859ab4ad0c890f59",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"20px",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":183,
                                "height":52},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"Case 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open !Recomend_1 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"_recomend_1.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/home/u21.png"}},
{
                        "id":"d95218d3a5894504a44fad0c51d22001",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":52},
                          "size":{
                            "width":183,
                            "height":28},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"ca77b8d2026844908ce20fb529f62b75",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"20px",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":52},
                              "size":{
                                "width":183,
                                "height":28},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/home/u23.png"}},
{
                        "id":"7099eefa6fba4881af72c12718122013",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":183,
                            "height":52},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"9aa0b348d01d48f3b73caddff9a4c394",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"20px",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":80},
                              "size":{
                                "width":183,
                                "height":52},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/home/u21.png"}},
{
                        "id":"56e892457d674da3b1c1698007cb7ef0",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":132},
                          "size":{
                            "width":183,
                            "height":52},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"2c778d6550b644c486976c478a7d72e5",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"20px",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":132},
                              "size":{
                                "width":183,
                                "height":52},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/home/u27.png"}}]}],
                "parentCellId":"774d22def07f4b3b92beaf7d3113c8e3"}]},
{
            "id":"0f0ce908cb5e4e668e2051a152a009ac",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":-28},
              "size":{
                "width":580,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a3eac7c066243798a5b2c6235b26a0e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":-28},
                  "size":{
                    "width":580,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u29.jpg"}},
{
            "id":"00fdbbc6f18a432fb754444bec683a49",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1207,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2d93413044cbfac754e65e456484a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1207,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u31.png"}},
{
            "id":"2b5505a026064198ae5312894c44877b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1165,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb4c16b29de94517bf081a61ec087285",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1165,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"1b1cbe0241714a378a81b178b0e86735",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1123,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c8fefe866140448f1e15b946398de4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1123,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u35.png"}},
{
            "id":"fbe7887b2aad40989761f1b43212d52b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1081,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4cd45276529f4bfcb293119e311b3986",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1081,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u37.png"}},
{
            "id":"db9085386ae0403b872a52d3388be44d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":12,
                "y":8},
              "size":{
                "width":318,
                "height":57}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c72d5500e5974604a2afbae40f0bcab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":12,
                    "y":8},
                  "size":{
                    "width":318,
                    "height":57}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f6f939892ba64f94b76ad834e47d4b82",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":16,
                "y":64},
              "size":{
                "width":304,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"edfd1d481b144801bf684f564d0f14e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":16,
                    "y":64},
                  "size":{
                    "width":304,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb0d2181a3c346fda67248f2169af96c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":16,
                "y":-9},
              "size":{
                "width":108,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"01f1ed0e703140aaac8556b31d9fdc11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":-9},
                  "size":{
                    "width":108,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"48be34192e0a4fa5925bc7074e0e92f1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"22px",
              "location":{
                "x":1006,
                "y":-7},
              "size":{
                "width":44,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"373f4e85b54046ab84cbd7d14d4188ce",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"22px",
                  "location":{
                    "x":1006,
                    "y":-7},
                  "size":{
                    "width":44,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "1c043ff96f1947a9b4613e78a73b6b0b":{
      "packageId":"1c043ff96f1947a9b4613e78a73b6b0b",
      "type":"Axure:Master",
      "name":"Футер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9fc91ae066174b309c3f0d46fe8888fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-10,
                "y":0},
              "size":{
                "width":1280,
                "height":300}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"66be155d52ee42588ea72dbc1f055f90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-10,
                    "y":0},
                  "size":{
                    "width":1280,
                    "height":300}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u48.png"}},
{
            "id":"ddea022546f74b6fa41947b0291e2334",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":30,
                "y":14},
              "size":{
                "width":101,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89f2e4dfdcaf410fa5ba9dd499dc91b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":30,
                    "y":14},
                  "size":{
                    "width":101,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f5eb2795b014e089f2a0a4dcc667061",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":53},
              "size":{
                "width":70,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"763500db2a414e9e8c8b8a14e1d09b1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":53},
                  "size":{
                    "width":70,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b333f7fb5b88469b8dd4f8a599b79e6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":85},
              "size":{
                "width":68,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a84e81a6f8fd42b0a235a0ddca308e2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":85},
                  "size":{
                    "width":68,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"eda8c6e1c5184795bf3b637a1369fe9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":117},
              "size":{
                "width":64,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19eb2d053ee740da8b420086cb0ed542",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":117},
                  "size":{
                    "width":64,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bd067fad9b9d48deb6e6c41eb0492c8a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":332,
                "y":14},
              "size":{
                "width":160,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fcdd4cbfa904ec8aeac78a1a733ad40",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":332,
                    "y":14},
                  "size":{
                    "width":160,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce3bd7deeed248f89cf82ca82eeeed3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":332,
                "y":50},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92f32b9871b54ea6a20d2ecc7241d883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":332,
                    "y":50},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"11ad65cd45e84f4b95f147f21f1657c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":680,
                "y":14},
              "size":{
                "width":98,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93173ecf7ca04258870af0834f832b53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":680,
                    "y":14},
                  "size":{
                    "width":98,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e024c2b6a9384da7b6c1c8db894e3fd0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":50},
              "size":{
                "width":153,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80655206f5704739b7a76c9bd5754d26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":50},
                  "size":{
                    "width":153,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6d49b834c588458686a066d938e026be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":989,
                "y":14},
              "size":{
                "width":167,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe5fbb369ebb4ac8b1ee950406136e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":989,
                    "y":14},
                  "size":{
                    "width":167,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f663051151124546aa320df44882e86a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":989.000061035156,
                "y":50},
              "size":{
                "width":221,
                "height":220}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d76f835091e4469ea3d2706eb50c48ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":989.000061035156,
                    "y":50},
                  "size":{
                    "width":221,
                    "height":220}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u68.jpg"}},
{
            "id":"1cf32189befe4fe2bff08a5095974b0f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":159},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48dfd1fc634a4d5383a086db0d2c2604",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":159},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u70.png"}},
{
            "id":"ffe38148cf74490888da731228dad2c3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":740,
                "y":176},
              "size":{
                "width":101,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"076390907da442c5873080a95cdaf7f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":740,
                    "y":176},
                  "size":{
                    "width":101,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ab7c9753ece44de0af0637a216188e24",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":219},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1aee3f32134c4be0848277842ea15268",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":219},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u70.png"}},
{
            "id":"bd903b22dcfb403aad7f42f835a7091e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":740,
                "y":236},
              "size":{
                "width":81,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ab6aa297e717408ab4bba582e7c999b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":740,
                    "y":236},
                  "size":{
                    "width":81,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "8d1eb8e4fd58486580956464f1be7d76":{
      "scriptId":"u0",
      "a24d26dd8cbf4f848f51c061f19d3ec2":{
        "scriptId":"u1"},
      "ad4a5933465143999cd6214d999692d6":{
        "scriptId":"u2"},
      "1986c1faae294ce5b785ebea9c9954d1":{
        "scriptId":"u3"},
      "b476c7edf27f4f47a1e333f7f8061d5e":{
        "scriptId":"u4"},
      "2008e102df584d74a483975847661c17":{
        "scriptId":"u5"},
      "824e543911104969870ab12502c80eda":{
        "scriptId":"u6"},
      "b51e264b43464b27af113cbf070b274d":{
        "scriptId":"u7"},
      "0e31ad92b7bc4eeb941d4fc5633165db":{
        "scriptId":"u8"},
      "94faf73cf2a140e1b5a65136362028b0":{
        "scriptId":"u9"},
      "24f6277a43d84fe58c2bcc94f1624738":{
        "scriptId":"u10"},
      "41195ca2d4eb4b25b02f328962a88fea":{
        "scriptId":"u11"},
      "262376ede03e425c805a7ee916d5dc4d":{
        "scriptId":"u12"},
      "774d22def07f4b3b92beaf7d3113c8e3":{
        "scriptId":"u13"},
      "f3ade7596611440d93de5a3f4d363b75":{
        "scriptId":"u14"},
      "9bba04f51c5e482eab48c197c0c5363f":{
        "scriptId":"u15"},
      "782008b02e71410c967b33d141b84e61":{
        "scriptId":"u16"},
      "24db02bcbff8461cbea21ec682c852e4":{
        "scriptId":"u17"},
      "1c477273f7bd4c68b1992c1e467819a1":{
        "scriptId":"u18"},
      "9ac348a26857416bb79680212145b5ee":{
        "scriptId":"u19"},
      "57f74f87cb2b4977906ae56b1eff6a24":{
        "scriptId":"u20"},
      "aa6e42cab61645a796d2e7097ab11d74":{
        "scriptId":"u21"},
      "77b18f4acbcf48d1859ab4ad0c890f59":{
        "scriptId":"u22"},
      "d95218d3a5894504a44fad0c51d22001":{
        "scriptId":"u23"},
      "ca77b8d2026844908ce20fb529f62b75":{
        "scriptId":"u24"},
      "7099eefa6fba4881af72c12718122013":{
        "scriptId":"u25"},
      "9aa0b348d01d48f3b73caddff9a4c394":{
        "scriptId":"u26"},
      "56e892457d674da3b1c1698007cb7ef0":{
        "scriptId":"u27"},
      "2c778d6550b644c486976c478a7d72e5":{
        "scriptId":"u28"},
      "0f0ce908cb5e4e668e2051a152a009ac":{
        "scriptId":"u29"},
      "8a3eac7c066243798a5b2c6235b26a0e":{
        "scriptId":"u30"},
      "00fdbbc6f18a432fb754444bec683a49":{
        "scriptId":"u31"},
      "cdf2d93413044cbfac754e65e456484a":{
        "scriptId":"u32"},
      "2b5505a026064198ae5312894c44877b":{
        "scriptId":"u33"},
      "bb4c16b29de94517bf081a61ec087285":{
        "scriptId":"u34"},
      "1b1cbe0241714a378a81b178b0e86735":{
        "scriptId":"u35"},
      "68c8fefe866140448f1e15b946398de4":{
        "scriptId":"u36"},
      "fbe7887b2aad40989761f1b43212d52b":{
        "scriptId":"u37"},
      "4cd45276529f4bfcb293119e311b3986":{
        "scriptId":"u38"},
      "db9085386ae0403b872a52d3388be44d":{
        "scriptId":"u39"},
      "c72d5500e5974604a2afbae40f0bcab2":{
        "scriptId":"u40"},
      "f6f939892ba64f94b76ad834e47d4b82":{
        "scriptId":"u41"},
      "edfd1d481b144801bf684f564d0f14e2":{
        "scriptId":"u42"},
      "bb0d2181a3c346fda67248f2169af96c":{
        "scriptId":"u43"},
      "01f1ed0e703140aaac8556b31d9fdc11":{
        "scriptId":"u44"},
      "48be34192e0a4fa5925bc7074e0e92f1":{
        "scriptId":"u45"},
      "373f4e85b54046ab84cbd7d14d4188ce":{
        "scriptId":"u46"}},
    "9be071765d1444d4bc3647c3f5e59185":{
      "scriptId":"u47"},
    "9c8b250dcfc144a4b591a359a02b0b3d":{
      "scriptId":"u48"},
    "6864a621d8134e0093117dab22d3d578":{
      "scriptId":"u49"},
    "1c7d83ee9a3e436aaaec801e8da00d2d":{
      "scriptId":"u50"},
    "eb58455cc8d24a0e828128a5a6230c5b":{
      "scriptId":"u51"},
    "424ff4114d4843fab026724b461880d6":{
      "scriptId":"u52"},
    "3a43f0fbd80e4c4990914bc78c22532b":{
      "scriptId":"u53"},
    "2576311dd57b4f72b26ad7de5faf07c6":{
      "scriptId":"u54"},
    "f0fe002df9ae4cf8bbd3beff490dafdb":{
      "scriptId":"u55"},
    "ea4f3a12ccba4206828da3438d7c8935":{
      "scriptId":"u56"},
    "7c0206cc196349b4a2fdd4e48855976e":{
      "scriptId":"u57"},
    "f4999b67d7aa48bbbf962929b119ba65":{
      "scriptId":"u58"},
    "4e0b9c83f9cd457883417949458d2761":{
      "scriptId":"u59"},
    "5410eff50dc545609aa96e02c76d6ab3":{
      "scriptId":"u60"},
    "8c3047f77deb4af4a933fa922c36fa62":{
      "scriptId":"u61"},
    "b7ea4a932d7442639c343bc7b3e5be78":{
      "scriptId":"u62"},
    "ea63b3a425b94270a4af689c60d90616":{
      "scriptId":"u63"},
    "073cb1ddce5f41069d2addc752e5b8e7":{
      "scriptId":"u64"},
    "ffcf6beeb0044cabbeedd988c17ab00e":{
      "scriptId":"u65"},
    "49a6da6f1a7447d1a117f11dc6726dc1":{
      "scriptId":"u66"},
    "5c16768c64f847e4b14e19c20490eb44":{
      "scriptId":"u67"},
    "84e2bf8d40d2424aae781d0430d74f11":{
      "scriptId":"u68"},
    "98c6ad4fd61d4dc885bae17eed65c27b":{
      "scriptId":"u69",
      "9fc91ae066174b309c3f0d46fe8888fb":{
        "scriptId":"u70"},
      "66be155d52ee42588ea72dbc1f055f90":{
        "scriptId":"u71"},
      "ddea022546f74b6fa41947b0291e2334":{
        "scriptId":"u72"},
      "89f2e4dfdcaf410fa5ba9dd499dc91b8":{
        "scriptId":"u73"},
      "9f5eb2795b014e089f2a0a4dcc667061":{
        "scriptId":"u74"},
      "763500db2a414e9e8c8b8a14e1d09b1a":{
        "scriptId":"u75"},
      "b333f7fb5b88469b8dd4f8a599b79e6a":{
        "scriptId":"u76"},
      "a84e81a6f8fd42b0a235a0ddca308e2a":{
        "scriptId":"u77"},
      "eda8c6e1c5184795bf3b637a1369fe9d":{
        "scriptId":"u78"},
      "19eb2d053ee740da8b420086cb0ed542":{
        "scriptId":"u79"},
      "bd067fad9b9d48deb6e6c41eb0492c8a":{
        "scriptId":"u80"},
      "5fcdd4cbfa904ec8aeac78a1a733ad40":{
        "scriptId":"u81"},
      "ce3bd7deeed248f89cf82ca82eeeed3f":{
        "scriptId":"u82"},
      "92f32b9871b54ea6a20d2ecc7241d883":{
        "scriptId":"u83"},
      "11ad65cd45e84f4b95f147f21f1657c2":{
        "scriptId":"u84"},
      "93173ecf7ca04258870af0834f832b53":{
        "scriptId":"u85"},
      "e024c2b6a9384da7b6c1c8db894e3fd0":{
        "scriptId":"u86"},
      "80655206f5704739b7a76c9bd5754d26":{
        "scriptId":"u87"},
      "6d49b834c588458686a066d938e026be":{
        "scriptId":"u88"},
      "fe5fbb369ebb4ac8b1ee950406136e69":{
        "scriptId":"u89"},
      "f663051151124546aa320df44882e86a":{
        "scriptId":"u90"},
      "d76f835091e4469ea3d2706eb50c48ae":{
        "scriptId":"u91"},
      "1cf32189befe4fe2bff08a5095974b0f":{
        "scriptId":"u92"},
      "48dfd1fc634a4d5383a086db0d2c2604":{
        "scriptId":"u93"},
      "ffe38148cf74490888da731228dad2c3":{
        "scriptId":"u94"},
      "076390907da442c5873080a95cdaf7f4":{
        "scriptId":"u95"},
      "ab7c9753ece44de0af0637a216188e24":{
        "scriptId":"u96"},
      "1aee3f32134c4be0848277842ea15268":{
        "scriptId":"u97"},
      "bd903b22dcfb403aad7f42f835a7091e":{
        "scriptId":"u98"},
      "ab6aa297e717408ab4bba582e7c999b8":{
        "scriptId":"u99"}}}});