$axure.loadCurrentPage({
  "url":"about.html",
  "generationDate":new Date(1423593362763.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f76b148dc43d4505b83640d7f3fcdea2",
    "type":"Axure:Page",
    "name":"About",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6c5f8b90e67a4016935e087d92ec8ab9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"3c2651543160467bb6dbd1c6e4fb5ae6"},
{
          "id":"5b44f6aaf25649bb9546c8fa0b9fcfb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":207},
            "size":{
              "width":1280,
              "height":1573}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08066173ae85483b9888ff18690851ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":207},
                "size":{
                  "width":1280,
                  "height":1573}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u36.png"}},
{
          "id":"7ecbae6e8d3f45069b6036263156026d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":537,
              "y":226},
            "size":{
              "width":144,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fe7ad8311704612a16e0f1997ce4f55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":537,
                  "y":226},
                "size":{
                  "width":144,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07e91053addd4e52a1173918a916bccc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":50,
              "y":284},
            "size":{
              "width":1180,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59666862ec5d4e82b5de6b7d1f8ef435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":50,
                  "y":284},
                "size":{
                  "width":1180,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50a11c44cdc9439db2ec4ed33fd2dc97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":469},
            "size":{
              "width":160,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ff09f959f064c64b8a166578f4e0c18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":469},
                "size":{
                  "width":160,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u42.png"}},
{
          "id":"8322592cb1524f768195cece8fb80ab5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":469},
            "size":{
              "width":160,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c5bfc52378b40bfb7c5b8383b7c1633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":469},
                "size":{
                  "width":160,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u42.png"}},
{
          "id":"0f34f1300d534e44824dc61c286f0a8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":469},
            "size":{
              "width":160,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe102acd670f4db39bd30d69ff2cacbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":469},
                "size":{
                  "width":160,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u42.png"}},
{
          "id":"ee3f27cb14f4488db09fd8527b5126ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":314.5,
              "y":400},
            "size":{
              "width":651,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5d3cb56c6f64bcd89ba77076345a7ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":314.5,
                  "y":400},
                "size":{
                  "width":651,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27b93ba5b4684042a0688673ae1efd89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":640,
              "y":469},
            "size":{
              "width":588,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cff1141ba0ef4ee0ba61f1f738ab0def",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":640,
                  "y":469},
                "size":{
                  "width":588,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"673372f1fffd481eb468f54f43ee6001",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":740},
            "size":{
              "width":670,
              "height":362}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ac14249c494458a94ba92b55677393e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":740},
                "size":{
                  "width":670,
                  "height":362}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u52.jpg"}},
{
          "id":"f3ff39ac45a94f20906261384c81f4ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":821.5},
            "size":{
              "width":200,
              "height":199}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"032b75793ace4492b839dd1aee9a7abf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":821.5},
                "size":{
                  "width":200,
                  "height":199}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u54.png"}},
{
          "id":"18391e11a7d4402b874ad3c36fa9e04b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "location":{
              "x":567,
              "y":678},
            "size":{
              "width":114,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87c09d5d510d404d89e37f383bf29250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "location":{
                  "x":567,
                  "y":678},
                "size":{
                  "width":114,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02bf16d73ab9402f95527f69f6d29034",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":750,
              "y":740},
            "size":{
              "width":478,
              "height":362}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a3684a310144f1e9246f4ac8057836a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":750,
                  "y":740},
                "size":{
                  "width":478,
                  "height":362}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6828aff24ec948c9b111ef5a128537aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "location":{
              "x":385,
              "y":1138},
            "size":{
              "width":478,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df20a317f5ce4d1fbe5c085b1a57baa8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "location":{
                  "x":385,
                  "y":1138},
                "size":{
                  "width":478,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5add7ae472e34731865d45c5f703db45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":412,
              "y":1216},
            "size":{
              "width":814,
              "height":194}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"202a857e6e8542728293ef2c9b295d7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":412,
                  "y":1216},
                "size":{
                  "width":814,
                  "height":194}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7739b60e7564d8eb773bd19b752260c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "location":{
              "x":533,
              "y":1498},
            "size":{
              "width":182,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d6725deb8124ee581998127f48117a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "location":{
                  "x":533,
                  "y":1498},
                "size":{
                  "width":182,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"183f9197a1d04a1db8c97dadb9a10b2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":50,
              "y":655},
            "size":{
              "width":570,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b33fd7e79df4ecba7dbc2e59e9147d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":50,
                  "y":655},
                "size":{
                  "width":570,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e549c0842b3e41b6bcb20cda6d8822c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":1216},
            "size":{
              "width":330,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ed91ae8b98c431d8ad41d82fe88cc16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":1216},
                "size":{
                  "width":330,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u68.png"}},
{
          "id":"1d10eb3ed54a4766af7c48a47bcdca20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1558},
            "size":{
              "width":162,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ba006bd57aa469789dc2f35f590c9fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1558},
                "size":{
                  "width":162,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u70.png"}},
{
          "id":"a0f5eebadaac45a5b8df200193b718f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":78,
              "y":1708},
            "size":{
              "width":126,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6851cde6f83f40e69b83f6463db716b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":78,
                  "y":1708},
                "size":{
                  "width":126,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e060dd52d4084039945c22e4f8095ebf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":1558},
            "size":{
              "width":162,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c95d60917c37431c9697e7d5f4d54bf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":1558},
                "size":{
                  "width":162,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u70.png"}},
{
          "id":"62127b1618ba4433af305ec3905f2536",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":278,
              "y":1708},
            "size":{
              "width":126,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9fe66a46c9344b9839c52d72475521a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":278,
                  "y":1708},
                "size":{
                  "width":126,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66fb03a3097d4f34aa53fb060075ccf9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":1558},
            "size":{
              "width":162,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72e7269664504f47833cdc78dc57b233",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":1558},
                "size":{
                  "width":162,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u70.png"}},
{
          "id":"f4bff75536de48008a809a2f0fa47d91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":470,
              "y":1708},
            "size":{
              "width":126,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4556ba8cf7a94066b28f8a83e1eb0a7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":470,
                  "y":1708},
                "size":{
                  "width":126,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf4bd3b7b5d54c46a1177a77b824fac4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":652,
              "y":1558},
            "size":{
              "width":162,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51b874bb4c614105ae33592d2c327155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":652,
                  "y":1558},
                "size":{
                  "width":162,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u70.png"}},
{
          "id":"666765fd83ef4341ab7621351a0e5174",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":670,
              "y":1708},
            "size":{
              "width":126,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c1538c40cda44f5b3d0e82c7afd1365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":670,
                  "y":1708},
                "size":{
                  "width":126,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5885e78e0594252bbe3587f52f2d7a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":852,
              "y":1558},
            "size":{
              "width":162,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23fedc5cd9be4707aa09d30ad7fd986c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":852,
                  "y":1558},
                "size":{
                  "width":162,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u70.png"}},
{
          "id":"e1f1186246034a6b93d7ab26a7e40986",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":870,
              "y":1708},
            "size":{
              "width":126,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd6536525d44406093c3925f8af80f69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":870,
                  "y":1708},
                "size":{
                  "width":126,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"892c6032b643433184afcb9b08ac18f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1044,
              "y":1558},
            "size":{
              "width":162,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1718d5231de14b66a9ad3affa61c3e8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1044,
                  "y":1558},
                "size":{
                  "width":162,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/about/u70.png"}},
{
          "id":"97753af571ce41de978630885a4a75cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":1062,
              "y":1708},
            "size":{
              "width":126,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"500adf7fc4294e598a43d31ae6747597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":1062,
                  "y":1708},
                "size":{
                  "width":126,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7164d3cb58b743999c9af93d47c600db",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1780}},
          "adaptiveStyles":{
},
          "masterId":"1c043ff96f1947a9b4613e78a73b6b0b"}]}},
  "masters":{
    "3c2651543160467bb6dbd1c6e4fb5ae6":{
      "packageId":"3c2651543160467bb6dbd1c6e4fb5ae6",
      "type":"Axure:Master",
      "name":"Хидер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a24d26dd8cbf4f848f51c061f19d3ec2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-30},
              "size":{
                "width":1280,
                "height":207}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad4a5933465143999cd6214d999692d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-30},
                  "size":{
                    "width":1280,
                    "height":207}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"1986c1faae294ce5b785ebea9c9954d1",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":109},
              "size":{
                "width":950,
                "height":68}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b476c7edf27f4f47a1e333f7f8061d5e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":950,
                    "height":68}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2008e102df584d74a483975847661c17",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"824e543911104969870ab12502c80eda",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"b51e264b43464b27af113cbf070b274d",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":190,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0e31ad92b7bc4eeb941d4fc5633165db",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":190,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Category in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"category.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"94faf73cf2a140e1b5a65136362028b0",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":380,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"24f6277a43d84fe58c2bcc94f1624738",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":380,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"41195ca2d4eb4b25b02f328962a88fea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":570,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"262376ede03e425c805a7ee916d5dc4d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":570,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"774d22def07f4b3b92beaf7d3113c8e3",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":760,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f3ade7596611440d93de5a3f4d363b75",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":760,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u17.png"}}]}]},
{
            "id":"0f0ce908cb5e4e668e2051a152a009ac",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":-28.5},
              "size":{
                "width":480,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a3eac7c066243798a5b2c6235b26a0e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":-28.5},
                  "size":{
                    "width":480,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"63bef173bd0141fc9010fbfe0fd9b35c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "location":{
                "x":1114,
                "y":56},
              "size":{
                "width":107,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"310aa94f3d31441c9e33bfd9c9646e91",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "location":{
                    "x":1114,
                    "y":56},
                  "size":{
                    "width":107,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"00fdbbc6f18a432fb754444bec683a49",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1207,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2d93413044cbfac754e65e456484a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1207,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u23.png"}},
{
            "id":"2b5505a026064198ae5312894c44877b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1165,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb4c16b29de94517bf081a61ec087285",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1165,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u25.png"}},
{
            "id":"1b1cbe0241714a378a81b178b0e86735",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1123,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c8fefe866140448f1e15b946398de4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1123,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fbe7887b2aad40989761f1b43212d52b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1081,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4cd45276529f4bfcb293119e311b3986",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1081,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"db9085386ae0403b872a52d3388be44d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":12,
                "y":8},
              "size":{
                "width":318,
                "height":57}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c72d5500e5974604a2afbae40f0bcab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":12,
                    "y":8},
                  "size":{
                    "width":318,
                    "height":57}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f6f939892ba64f94b76ad834e47d4b82",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":16,
                "y":64},
              "size":{
                "width":304,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"edfd1d481b144801bf684f564d0f14e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":16,
                    "y":64},
                  "size":{
                    "width":304,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb0d2181a3c346fda67248f2169af96c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":16,
                "y":-9},
              "size":{
                "width":108,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"01f1ed0e703140aaac8556b31d9fdc11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":-9},
                  "size":{
                    "width":108,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"885685ceb66b434e863ffd0845fa2b42",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1094,
                "y":54},
              "size":{
                "width":10,
                "height":32}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u37_line.png"}},
{
            "id":"82b50fcf1e0e409d9a5a12e93a7f8f67",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "location":{
                "x":980,
                "y":56},
              "size":{
                "width":104,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b12036b93c294313a4203a7ee8ea1f7c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "location":{
                    "x":980,
                    "y":56},
                  "size":{
                    "width":104,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open News in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "1c043ff96f1947a9b4613e78a73b6b0b":{
      "packageId":"1c043ff96f1947a9b4613e78a73b6b0b",
      "type":"Axure:Master",
      "name":"Футер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9fc91ae066174b309c3f0d46fe8888fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-10,
                "y":0},
              "size":{
                "width":1280,
                "height":300}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"66be155d52ee42588ea72dbc1f055f90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-10,
                    "y":0},
                  "size":{
                    "width":1280,
                    "height":300}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}},
{
            "id":"ddea022546f74b6fa41947b0291e2334",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":30,
                "y":14},
              "size":{
                "width":101,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89f2e4dfdcaf410fa5ba9dd499dc91b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":30,
                    "y":14},
                  "size":{
                    "width":101,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f5eb2795b014e089f2a0a4dcc667061",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":53},
              "size":{
                "width":70,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"763500db2a414e9e8c8b8a14e1d09b1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":53},
                  "size":{
                    "width":70,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b333f7fb5b88469b8dd4f8a599b79e6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":85},
              "size":{
                "width":68,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a84e81a6f8fd42b0a235a0ddca308e2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":85},
                  "size":{
                    "width":68,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"eda8c6e1c5184795bf3b637a1369fe9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":117},
              "size":{
                "width":64,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19eb2d053ee740da8b420086cb0ed542",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":117},
                  "size":{
                    "width":64,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bd067fad9b9d48deb6e6c41eb0492c8a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":332,
                "y":14},
              "size":{
                "width":111,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fcdd4cbfa904ec8aeac78a1a733ad40",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":332,
                    "y":14},
                  "size":{
                    "width":111,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce3bd7deeed248f89cf82ca82eeeed3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":332,
                "y":50},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92f32b9871b54ea6a20d2ecc7241d883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":332,
                    "y":50},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"11ad65cd45e84f4b95f147f21f1657c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":680,
                "y":14},
              "size":{
                "width":98,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93173ecf7ca04258870af0834f832b53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":680,
                    "y":14},
                  "size":{
                    "width":98,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e024c2b6a9384da7b6c1c8db894e3fd0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":50},
              "size":{
                "width":153,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80655206f5704739b7a76c9bd5754d26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":50},
                  "size":{
                    "width":153,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6d49b834c588458686a066d938e026be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":989,
                "y":14},
              "size":{
                "width":167,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe5fbb369ebb4ac8b1ee950406136e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":989,
                    "y":14},
                  "size":{
                    "width":167,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f663051151124546aa320df44882e86a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":989.000061035156,
                "y":50},
              "size":{
                "width":221,
                "height":220}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d76f835091e4469ea3d2706eb50c48ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":989.000061035156,
                    "y":50},
                  "size":{
                    "width":221,
                    "height":220}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u61.jpg"}}]}}},
  "objectPaths":{
    "6c5f8b90e67a4016935e087d92ec8ab9":{
      "scriptId":"u0",
      "a24d26dd8cbf4f848f51c061f19d3ec2":{
        "scriptId":"u1"},
      "ad4a5933465143999cd6214d999692d6":{
        "scriptId":"u2"},
      "1986c1faae294ce5b785ebea9c9954d1":{
        "scriptId":"u3"},
      "b476c7edf27f4f47a1e333f7f8061d5e":{
        "scriptId":"u4"},
      "2008e102df584d74a483975847661c17":{
        "scriptId":"u5"},
      "824e543911104969870ab12502c80eda":{
        "scriptId":"u6"},
      "b51e264b43464b27af113cbf070b274d":{
        "scriptId":"u7"},
      "0e31ad92b7bc4eeb941d4fc5633165db":{
        "scriptId":"u8"},
      "94faf73cf2a140e1b5a65136362028b0":{
        "scriptId":"u9"},
      "24f6277a43d84fe58c2bcc94f1624738":{
        "scriptId":"u10"},
      "41195ca2d4eb4b25b02f328962a88fea":{
        "scriptId":"u11"},
      "262376ede03e425c805a7ee916d5dc4d":{
        "scriptId":"u12"},
      "774d22def07f4b3b92beaf7d3113c8e3":{
        "scriptId":"u13"},
      "f3ade7596611440d93de5a3f4d363b75":{
        "scriptId":"u14"},
      "0f0ce908cb5e4e668e2051a152a009ac":{
        "scriptId":"u15"},
      "8a3eac7c066243798a5b2c6235b26a0e":{
        "scriptId":"u16"},
      "63bef173bd0141fc9010fbfe0fd9b35c":{
        "scriptId":"u17"},
      "310aa94f3d31441c9e33bfd9c9646e91":{
        "scriptId":"u18"},
      "00fdbbc6f18a432fb754444bec683a49":{
        "scriptId":"u19"},
      "cdf2d93413044cbfac754e65e456484a":{
        "scriptId":"u20"},
      "2b5505a026064198ae5312894c44877b":{
        "scriptId":"u21"},
      "bb4c16b29de94517bf081a61ec087285":{
        "scriptId":"u22"},
      "1b1cbe0241714a378a81b178b0e86735":{
        "scriptId":"u23"},
      "68c8fefe866140448f1e15b946398de4":{
        "scriptId":"u24"},
      "fbe7887b2aad40989761f1b43212d52b":{
        "scriptId":"u25"},
      "4cd45276529f4bfcb293119e311b3986":{
        "scriptId":"u26"},
      "db9085386ae0403b872a52d3388be44d":{
        "scriptId":"u27"},
      "c72d5500e5974604a2afbae40f0bcab2":{
        "scriptId":"u28"},
      "f6f939892ba64f94b76ad834e47d4b82":{
        "scriptId":"u29"},
      "edfd1d481b144801bf684f564d0f14e2":{
        "scriptId":"u30"},
      "bb0d2181a3c346fda67248f2169af96c":{
        "scriptId":"u31"},
      "01f1ed0e703140aaac8556b31d9fdc11":{
        "scriptId":"u32"},
      "885685ceb66b434e863ffd0845fa2b42":{
        "scriptId":"u33"},
      "82b50fcf1e0e409d9a5a12e93a7f8f67":{
        "scriptId":"u34"},
      "b12036b93c294313a4203a7ee8ea1f7c":{
        "scriptId":"u35"}},
    "5b44f6aaf25649bb9546c8fa0b9fcfb2":{
      "scriptId":"u36"},
    "08066173ae85483b9888ff18690851ce":{
      "scriptId":"u37"},
    "7ecbae6e8d3f45069b6036263156026d":{
      "scriptId":"u38"},
    "2fe7ad8311704612a16e0f1997ce4f55":{
      "scriptId":"u39"},
    "07e91053addd4e52a1173918a916bccc":{
      "scriptId":"u40"},
    "59666862ec5d4e82b5de6b7d1f8ef435":{
      "scriptId":"u41"},
    "50a11c44cdc9439db2ec4ed33fd2dc97":{
      "scriptId":"u42"},
    "5ff09f959f064c64b8a166578f4e0c18":{
      "scriptId":"u43"},
    "8322592cb1524f768195cece8fb80ab5":{
      "scriptId":"u44"},
    "7c5bfc52378b40bfb7c5b8383b7c1633":{
      "scriptId":"u45"},
    "0f34f1300d534e44824dc61c286f0a8f":{
      "scriptId":"u46"},
    "fe102acd670f4db39bd30d69ff2cacbb":{
      "scriptId":"u47"},
    "ee3f27cb14f4488db09fd8527b5126ce":{
      "scriptId":"u48"},
    "a5d3cb56c6f64bcd89ba77076345a7ae":{
      "scriptId":"u49"},
    "27b93ba5b4684042a0688673ae1efd89":{
      "scriptId":"u50"},
    "cff1141ba0ef4ee0ba61f1f738ab0def":{
      "scriptId":"u51"},
    "673372f1fffd481eb468f54f43ee6001":{
      "scriptId":"u52"},
    "0ac14249c494458a94ba92b55677393e":{
      "scriptId":"u53"},
    "f3ff39ac45a94f20906261384c81f4ea":{
      "scriptId":"u54"},
    "032b75793ace4492b839dd1aee9a7abf":{
      "scriptId":"u55"},
    "18391e11a7d4402b874ad3c36fa9e04b":{
      "scriptId":"u56"},
    "87c09d5d510d404d89e37f383bf29250":{
      "scriptId":"u57"},
    "02bf16d73ab9402f95527f69f6d29034":{
      "scriptId":"u58"},
    "8a3684a310144f1e9246f4ac8057836a":{
      "scriptId":"u59"},
    "6828aff24ec948c9b111ef5a128537aa":{
      "scriptId":"u60"},
    "df20a317f5ce4d1fbe5c085b1a57baa8":{
      "scriptId":"u61"},
    "5add7ae472e34731865d45c5f703db45":{
      "scriptId":"u62"},
    "202a857e6e8542728293ef2c9b295d7e":{
      "scriptId":"u63"},
    "c7739b60e7564d8eb773bd19b752260c":{
      "scriptId":"u64"},
    "6d6725deb8124ee581998127f48117a4":{
      "scriptId":"u65"},
    "183f9197a1d04a1db8c97dadb9a10b2d":{
      "scriptId":"u66"},
    "2b33fd7e79df4ecba7dbc2e59e9147d3":{
      "scriptId":"u67"},
    "e549c0842b3e41b6bcb20cda6d8822c6":{
      "scriptId":"u68"},
    "8ed91ae8b98c431d8ad41d82fe88cc16":{
      "scriptId":"u69"},
    "1d10eb3ed54a4766af7c48a47bcdca20":{
      "scriptId":"u70"},
    "1ba006bd57aa469789dc2f35f590c9fe":{
      "scriptId":"u71"},
    "a0f5eebadaac45a5b8df200193b718f9":{
      "scriptId":"u72"},
    "6851cde6f83f40e69b83f6463db716b7":{
      "scriptId":"u73"},
    "e060dd52d4084039945c22e4f8095ebf":{
      "scriptId":"u74"},
    "c95d60917c37431c9697e7d5f4d54bf4":{
      "scriptId":"u75"},
    "62127b1618ba4433af305ec3905f2536":{
      "scriptId":"u76"},
    "e9fe66a46c9344b9839c52d72475521a":{
      "scriptId":"u77"},
    "66fb03a3097d4f34aa53fb060075ccf9":{
      "scriptId":"u78"},
    "72e7269664504f47833cdc78dc57b233":{
      "scriptId":"u79"},
    "f4bff75536de48008a809a2f0fa47d91":{
      "scriptId":"u80"},
    "4556ba8cf7a94066b28f8a83e1eb0a7f":{
      "scriptId":"u81"},
    "cf4bd3b7b5d54c46a1177a77b824fac4":{
      "scriptId":"u82"},
    "51b874bb4c614105ae33592d2c327155":{
      "scriptId":"u83"},
    "666765fd83ef4341ab7621351a0e5174":{
      "scriptId":"u84"},
    "3c1538c40cda44f5b3d0e82c7afd1365":{
      "scriptId":"u85"},
    "b5885e78e0594252bbe3587f52f2d7a4":{
      "scriptId":"u86"},
    "23fedc5cd9be4707aa09d30ad7fd986c":{
      "scriptId":"u87"},
    "e1f1186246034a6b93d7ab26a7e40986":{
      "scriptId":"u88"},
    "fd6536525d44406093c3925f8af80f69":{
      "scriptId":"u89"},
    "892c6032b643433184afcb9b08ac18f2":{
      "scriptId":"u90"},
    "1718d5231de14b66a9ad3affa61c3e8e":{
      "scriptId":"u91"},
    "97753af571ce41de978630885a4a75cd":{
      "scriptId":"u92"},
    "500adf7fc4294e598a43d31ae6747597":{
      "scriptId":"u93"},
    "7164d3cb58b743999c9af93d47c600db":{
      "scriptId":"u94",
      "9fc91ae066174b309c3f0d46fe8888fb":{
        "scriptId":"u95"},
      "66be155d52ee42588ea72dbc1f055f90":{
        "scriptId":"u96"},
      "ddea022546f74b6fa41947b0291e2334":{
        "scriptId":"u97"},
      "89f2e4dfdcaf410fa5ba9dd499dc91b8":{
        "scriptId":"u98"},
      "9f5eb2795b014e089f2a0a4dcc667061":{
        "scriptId":"u99"},
      "763500db2a414e9e8c8b8a14e1d09b1a":{
        "scriptId":"u100"},
      "b333f7fb5b88469b8dd4f8a599b79e6a":{
        "scriptId":"u101"},
      "a84e81a6f8fd42b0a235a0ddca308e2a":{
        "scriptId":"u102"},
      "eda8c6e1c5184795bf3b637a1369fe9d":{
        "scriptId":"u103"},
      "19eb2d053ee740da8b420086cb0ed542":{
        "scriptId":"u104"},
      "bd067fad9b9d48deb6e6c41eb0492c8a":{
        "scriptId":"u105"},
      "5fcdd4cbfa904ec8aeac78a1a733ad40":{
        "scriptId":"u106"},
      "ce3bd7deeed248f89cf82ca82eeeed3f":{
        "scriptId":"u107"},
      "92f32b9871b54ea6a20d2ecc7241d883":{
        "scriptId":"u108"},
      "11ad65cd45e84f4b95f147f21f1657c2":{
        "scriptId":"u109"},
      "93173ecf7ca04258870af0834f832b53":{
        "scriptId":"u110"},
      "e024c2b6a9384da7b6c1c8db894e3fd0":{
        "scriptId":"u111"},
      "80655206f5704739b7a76c9bd5754d26":{
        "scriptId":"u112"},
      "6d49b834c588458686a066d938e026be":{
        "scriptId":"u113"},
      "fe5fbb369ebb4ac8b1ee950406136e69":{
        "scriptId":"u114"},
      "f663051151124546aa320df44882e86a":{
        "scriptId":"u115"},
      "d76f835091e4469ea3d2706eb50c48ae":{
        "scriptId":"u116"}}}});