$axure.loadCurrentPage({
  "url":"news.html",
  "generationDate":new Date(1423593365450.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7644808e3c4543a68100a70d16e0a79a",
    "type":"Axure:Page",
    "name":"News",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aa8363b288ba44a09149bb66334e4db1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":11}},
          "adaptiveStyles":{
},
          "masterId":"3c2651543160467bb6dbd1c6e4fb5ae6"},
{
          "id":"9e71febe44ff4079a4e68bfb36cf8c1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":218},
            "size":{
              "width":1280,
              "height":787}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b411886ad54443ba2f0c332a0ec3d78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":218},
                "size":{
                  "width":1280,
                  "height":787}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news/u36.png"}},
{
          "id":"46584ea7532c4217905db04b4130b293",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1004}},
          "adaptiveStyles":{
},
          "masterId":"1c043ff96f1947a9b4613e78a73b6b0b"},
{
          "id":"d7d1db5b503f4f2986cf69052abceb64",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":420},
            "size":{
              "width":850,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/news/u61_line.png"}},
{
          "id":"72f1f1a87df345d294c5af3158fc3513",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":856,
              "y":220},
            "size":{
              "width":10,
              "height":780}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/news/u62_line.png"}},
{
          "id":"dbe8be22af1e4fef81c1804a852a8e95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":864,
              "y":221},
            "size":{
              "width":425,
              "height":392}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8320ec1932204030be602a492551215a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":864,
                  "y":221},
                "size":{
                  "width":425,
                  "height":392}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/project/u77.jpg"}},
{
          "id":"dd03561b47594f0f80cd6269da55ccd7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":864,
              "y":612},
            "size":{
              "width":425,
              "height":392}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f303d269dc6f43de94f289ed9b3642a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":864,
                  "y":612},
                "size":{
                  "width":425,
                  "height":392}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/project/u77.jpg"}},
{
          "id":"ebe7be83f7484884b5d8242a3cb35c5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"700",
            "location":{
              "x":347,
              "y":228},
            "size":{
              "width":159,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"813d3776fa34490e970a8ec10e9e2799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"700",
                "location":{
                  "x":347,
                  "y":228},
                "size":{
                  "width":159,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"637cf34df6764245985ab6225759ecb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":18,
              "y":274},
            "size":{
              "width":253,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c028f97db7354fd0bcb1e214a2ac3ad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":18,
                  "y":274},
                "size":{
                  "width":253,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e62aeab59914986b76a2a09484289d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":300},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1cfea6a54a64b38b416c3a252e2a35e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":300},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"933fea82c534467c87517d2204a69efe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":18,
              "y":326},
            "size":{
              "width":792,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a897526d0d0347ccb7e57bb4c230d490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":18,
                  "y":326},
                "size":{
                  "width":792,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a1bd643f200441ba251aa3b707ac9ab",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":586},
            "size":{
              "width":850,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/news/u61_line.png"}},
{
          "id":"909a1ca4e1424ab89adc9dc43da269db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":18,
              "y":440.000030517578},
            "size":{
              "width":253,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8fd11d1ec784e03891c62de0f364053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":18,
                  "y":440.000030517578},
                "size":{
                  "width":253,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b8f1e58a9d9487b816cefaba68a9c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":466.000030517578},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f46329d053604f279234608f85d74a6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":466.000030517578},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b517f5619a404020878e5d3129a4d580",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":18,
              "y":492.000030517578},
            "size":{
              "width":792,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b20dc27c96c432aafb14b024f58f503",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":18,
                  "y":492.000030517578},
                "size":{
                  "width":792,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0e4c5d9d610424dbfd4fa31683afe13",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":752},
            "size":{
              "width":850,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/news/u61_line.png"}},
{
          "id":"7348216555af4de4ac1e6d92d483efe9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":18,
              "y":606},
            "size":{
              "width":253,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14be4af3915f4d709b068957b275589b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":18,
                  "y":606},
                "size":{
                  "width":253,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db927e6d9c1042198c0cd54e6e65fc23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":632},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7892495d36845f5a1337029e7f6ece4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":632},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03bfbe5f778040d383a8e7cf1dd322a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":18,
              "y":658},
            "size":{
              "width":792,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1f1e3cfaf864f8187d4f6bebf2f86b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":18,
                  "y":658},
                "size":{
                  "width":792,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad4c5d9ef50644deb60556da3b6c7a62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":18,
              "y":772},
            "size":{
              "width":253,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40d72e8ed1bf4ec7820da4e8e5b3cf6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":18,
                  "y":772},
                "size":{
                  "width":253,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84dff80a80924a07a39df558bebf6eec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":798},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba7f7f28610844f7aef2677d4d014e16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":798},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08c171601c8b4627bc1e17a2a776a6b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":18,
              "y":824},
            "size":{
              "width":792,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7f967a6d6ad40719724931be719df91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":18,
                  "y":824},
                "size":{
                  "width":792,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "3c2651543160467bb6dbd1c6e4fb5ae6":{
      "packageId":"3c2651543160467bb6dbd1c6e4fb5ae6",
      "type":"Axure:Master",
      "name":"Хидер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a24d26dd8cbf4f848f51c061f19d3ec2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-30},
              "size":{
                "width":1280,
                "height":207}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad4a5933465143999cd6214d999692d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-30},
                  "size":{
                    "width":1280,
                    "height":207}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"1986c1faae294ce5b785ebea9c9954d1",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":109},
              "size":{
                "width":950,
                "height":68}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b476c7edf27f4f47a1e333f7f8061d5e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":950,
                    "height":68}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2008e102df584d74a483975847661c17",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"824e543911104969870ab12502c80eda",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"b51e264b43464b27af113cbf070b274d",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":190,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0e31ad92b7bc4eeb941d4fc5633165db",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":190,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Category in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"category.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"94faf73cf2a140e1b5a65136362028b0",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":380,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"24f6277a43d84fe58c2bcc94f1624738",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":380,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"41195ca2d4eb4b25b02f328962a88fea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":570,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"262376ede03e425c805a7ee916d5dc4d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":570,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"774d22def07f4b3b92beaf7d3113c8e3",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":760,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f3ade7596611440d93de5a3f4d363b75",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":760,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u17.png"}}]}]},
{
            "id":"0f0ce908cb5e4e668e2051a152a009ac",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":-28.5},
              "size":{
                "width":480,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a3eac7c066243798a5b2c6235b26a0e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":-28.5},
                  "size":{
                    "width":480,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"63bef173bd0141fc9010fbfe0fd9b35c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "location":{
                "x":1114,
                "y":56},
              "size":{
                "width":107,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"310aa94f3d31441c9e33bfd9c9646e91",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "location":{
                    "x":1114,
                    "y":56},
                  "size":{
                    "width":107,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"00fdbbc6f18a432fb754444bec683a49",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1207,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2d93413044cbfac754e65e456484a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1207,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u23.png"}},
{
            "id":"2b5505a026064198ae5312894c44877b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1165,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb4c16b29de94517bf081a61ec087285",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1165,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u25.png"}},
{
            "id":"1b1cbe0241714a378a81b178b0e86735",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1123,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c8fefe866140448f1e15b946398de4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1123,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fbe7887b2aad40989761f1b43212d52b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1081,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4cd45276529f4bfcb293119e311b3986",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1081,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"db9085386ae0403b872a52d3388be44d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":12,
                "y":8},
              "size":{
                "width":318,
                "height":57}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c72d5500e5974604a2afbae40f0bcab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":12,
                    "y":8},
                  "size":{
                    "width":318,
                    "height":57}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f6f939892ba64f94b76ad834e47d4b82",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":16,
                "y":64},
              "size":{
                "width":304,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"edfd1d481b144801bf684f564d0f14e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":16,
                    "y":64},
                  "size":{
                    "width":304,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb0d2181a3c346fda67248f2169af96c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":16,
                "y":-9},
              "size":{
                "width":108,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"01f1ed0e703140aaac8556b31d9fdc11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":-9},
                  "size":{
                    "width":108,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"885685ceb66b434e863ffd0845fa2b42",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1094,
                "y":54},
              "size":{
                "width":10,
                "height":32}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u37_line.png"}},
{
            "id":"82b50fcf1e0e409d9a5a12e93a7f8f67",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "location":{
                "x":980,
                "y":56},
              "size":{
                "width":104,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b12036b93c294313a4203a7ee8ea1f7c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "location":{
                    "x":980,
                    "y":56},
                  "size":{
                    "width":104,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open News in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "1c043ff96f1947a9b4613e78a73b6b0b":{
      "packageId":"1c043ff96f1947a9b4613e78a73b6b0b",
      "type":"Axure:Master",
      "name":"Футер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9fc91ae066174b309c3f0d46fe8888fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-10,
                "y":0},
              "size":{
                "width":1280,
                "height":300}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"66be155d52ee42588ea72dbc1f055f90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-10,
                    "y":0},
                  "size":{
                    "width":1280,
                    "height":300}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}},
{
            "id":"ddea022546f74b6fa41947b0291e2334",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":30,
                "y":14},
              "size":{
                "width":101,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89f2e4dfdcaf410fa5ba9dd499dc91b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":30,
                    "y":14},
                  "size":{
                    "width":101,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f5eb2795b014e089f2a0a4dcc667061",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":53},
              "size":{
                "width":70,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"763500db2a414e9e8c8b8a14e1d09b1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":53},
                  "size":{
                    "width":70,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b333f7fb5b88469b8dd4f8a599b79e6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":85},
              "size":{
                "width":68,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a84e81a6f8fd42b0a235a0ddca308e2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":85},
                  "size":{
                    "width":68,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"eda8c6e1c5184795bf3b637a1369fe9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":117},
              "size":{
                "width":64,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19eb2d053ee740da8b420086cb0ed542",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":117},
                  "size":{
                    "width":64,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bd067fad9b9d48deb6e6c41eb0492c8a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":332,
                "y":14},
              "size":{
                "width":111,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fcdd4cbfa904ec8aeac78a1a733ad40",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":332,
                    "y":14},
                  "size":{
                    "width":111,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce3bd7deeed248f89cf82ca82eeeed3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":332,
                "y":50},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92f32b9871b54ea6a20d2ecc7241d883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":332,
                    "y":50},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"11ad65cd45e84f4b95f147f21f1657c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":680,
                "y":14},
              "size":{
                "width":98,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93173ecf7ca04258870af0834f832b53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":680,
                    "y":14},
                  "size":{
                    "width":98,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e024c2b6a9384da7b6c1c8db894e3fd0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":50},
              "size":{
                "width":153,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80655206f5704739b7a76c9bd5754d26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":50},
                  "size":{
                    "width":153,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6d49b834c588458686a066d938e026be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":989,
                "y":14},
              "size":{
                "width":167,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe5fbb369ebb4ac8b1ee950406136e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":989,
                    "y":14},
                  "size":{
                    "width":167,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f663051151124546aa320df44882e86a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":989.000061035156,
                "y":50},
              "size":{
                "width":221,
                "height":220}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d76f835091e4469ea3d2706eb50c48ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":989.000061035156,
                    "y":50},
                  "size":{
                    "width":221,
                    "height":220}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u61.jpg"}}]}}},
  "objectPaths":{
    "aa8363b288ba44a09149bb66334e4db1":{
      "scriptId":"u0",
      "a24d26dd8cbf4f848f51c061f19d3ec2":{
        "scriptId":"u1"},
      "ad4a5933465143999cd6214d999692d6":{
        "scriptId":"u2"},
      "1986c1faae294ce5b785ebea9c9954d1":{
        "scriptId":"u3"},
      "b476c7edf27f4f47a1e333f7f8061d5e":{
        "scriptId":"u4"},
      "2008e102df584d74a483975847661c17":{
        "scriptId":"u5"},
      "824e543911104969870ab12502c80eda":{
        "scriptId":"u6"},
      "b51e264b43464b27af113cbf070b274d":{
        "scriptId":"u7"},
      "0e31ad92b7bc4eeb941d4fc5633165db":{
        "scriptId":"u8"},
      "94faf73cf2a140e1b5a65136362028b0":{
        "scriptId":"u9"},
      "24f6277a43d84fe58c2bcc94f1624738":{
        "scriptId":"u10"},
      "41195ca2d4eb4b25b02f328962a88fea":{
        "scriptId":"u11"},
      "262376ede03e425c805a7ee916d5dc4d":{
        "scriptId":"u12"},
      "774d22def07f4b3b92beaf7d3113c8e3":{
        "scriptId":"u13"},
      "f3ade7596611440d93de5a3f4d363b75":{
        "scriptId":"u14"},
      "0f0ce908cb5e4e668e2051a152a009ac":{
        "scriptId":"u15"},
      "8a3eac7c066243798a5b2c6235b26a0e":{
        "scriptId":"u16"},
      "63bef173bd0141fc9010fbfe0fd9b35c":{
        "scriptId":"u17"},
      "310aa94f3d31441c9e33bfd9c9646e91":{
        "scriptId":"u18"},
      "00fdbbc6f18a432fb754444bec683a49":{
        "scriptId":"u19"},
      "cdf2d93413044cbfac754e65e456484a":{
        "scriptId":"u20"},
      "2b5505a026064198ae5312894c44877b":{
        "scriptId":"u21"},
      "bb4c16b29de94517bf081a61ec087285":{
        "scriptId":"u22"},
      "1b1cbe0241714a378a81b178b0e86735":{
        "scriptId":"u23"},
      "68c8fefe866140448f1e15b946398de4":{
        "scriptId":"u24"},
      "fbe7887b2aad40989761f1b43212d52b":{
        "scriptId":"u25"},
      "4cd45276529f4bfcb293119e311b3986":{
        "scriptId":"u26"},
      "db9085386ae0403b872a52d3388be44d":{
        "scriptId":"u27"},
      "c72d5500e5974604a2afbae40f0bcab2":{
        "scriptId":"u28"},
      "f6f939892ba64f94b76ad834e47d4b82":{
        "scriptId":"u29"},
      "edfd1d481b144801bf684f564d0f14e2":{
        "scriptId":"u30"},
      "bb0d2181a3c346fda67248f2169af96c":{
        "scriptId":"u31"},
      "01f1ed0e703140aaac8556b31d9fdc11":{
        "scriptId":"u32"},
      "885685ceb66b434e863ffd0845fa2b42":{
        "scriptId":"u33"},
      "82b50fcf1e0e409d9a5a12e93a7f8f67":{
        "scriptId":"u34"},
      "b12036b93c294313a4203a7ee8ea1f7c":{
        "scriptId":"u35"}},
    "9e71febe44ff4079a4e68bfb36cf8c1e":{
      "scriptId":"u36"},
    "6b411886ad54443ba2f0c332a0ec3d78":{
      "scriptId":"u37"},
    "46584ea7532c4217905db04b4130b293":{
      "scriptId":"u38",
      "9fc91ae066174b309c3f0d46fe8888fb":{
        "scriptId":"u39"},
      "66be155d52ee42588ea72dbc1f055f90":{
        "scriptId":"u40"},
      "ddea022546f74b6fa41947b0291e2334":{
        "scriptId":"u41"},
      "89f2e4dfdcaf410fa5ba9dd499dc91b8":{
        "scriptId":"u42"},
      "9f5eb2795b014e089f2a0a4dcc667061":{
        "scriptId":"u43"},
      "763500db2a414e9e8c8b8a14e1d09b1a":{
        "scriptId":"u44"},
      "b333f7fb5b88469b8dd4f8a599b79e6a":{
        "scriptId":"u45"},
      "a84e81a6f8fd42b0a235a0ddca308e2a":{
        "scriptId":"u46"},
      "eda8c6e1c5184795bf3b637a1369fe9d":{
        "scriptId":"u47"},
      "19eb2d053ee740da8b420086cb0ed542":{
        "scriptId":"u48"},
      "bd067fad9b9d48deb6e6c41eb0492c8a":{
        "scriptId":"u49"},
      "5fcdd4cbfa904ec8aeac78a1a733ad40":{
        "scriptId":"u50"},
      "ce3bd7deeed248f89cf82ca82eeeed3f":{
        "scriptId":"u51"},
      "92f32b9871b54ea6a20d2ecc7241d883":{
        "scriptId":"u52"},
      "11ad65cd45e84f4b95f147f21f1657c2":{
        "scriptId":"u53"},
      "93173ecf7ca04258870af0834f832b53":{
        "scriptId":"u54"},
      "e024c2b6a9384da7b6c1c8db894e3fd0":{
        "scriptId":"u55"},
      "80655206f5704739b7a76c9bd5754d26":{
        "scriptId":"u56"},
      "6d49b834c588458686a066d938e026be":{
        "scriptId":"u57"},
      "fe5fbb369ebb4ac8b1ee950406136e69":{
        "scriptId":"u58"},
      "f663051151124546aa320df44882e86a":{
        "scriptId":"u59"},
      "d76f835091e4469ea3d2706eb50c48ae":{
        "scriptId":"u60"}},
    "d7d1db5b503f4f2986cf69052abceb64":{
      "scriptId":"u61"},
    "72f1f1a87df345d294c5af3158fc3513":{
      "scriptId":"u62"},
    "dbe8be22af1e4fef81c1804a852a8e95":{
      "scriptId":"u63"},
    "8320ec1932204030be602a492551215a":{
      "scriptId":"u64"},
    "dd03561b47594f0f80cd6269da55ccd7":{
      "scriptId":"u65"},
    "f303d269dc6f43de94f289ed9b3642a7":{
      "scriptId":"u66"},
    "ebe7be83f7484884b5d8242a3cb35c5a":{
      "scriptId":"u67"},
    "813d3776fa34490e970a8ec10e9e2799":{
      "scriptId":"u68"},
    "637cf34df6764245985ab6225759ecb2":{
      "scriptId":"u69"},
    "c028f97db7354fd0bcb1e214a2ac3ad6":{
      "scriptId":"u70"},
    "6e62aeab59914986b76a2a09484289d4":{
      "scriptId":"u71"},
    "d1cfea6a54a64b38b416c3a252e2a35e":{
      "scriptId":"u72"},
    "933fea82c534467c87517d2204a69efe":{
      "scriptId":"u73"},
    "a897526d0d0347ccb7e57bb4c230d490":{
      "scriptId":"u74"},
    "5a1bd643f200441ba251aa3b707ac9ab":{
      "scriptId":"u75"},
    "909a1ca4e1424ab89adc9dc43da269db":{
      "scriptId":"u76"},
    "b8fd11d1ec784e03891c62de0f364053":{
      "scriptId":"u77"},
    "0b8f1e58a9d9487b816cefaba68a9c26":{
      "scriptId":"u78"},
    "f46329d053604f279234608f85d74a6c":{
      "scriptId":"u79"},
    "b517f5619a404020878e5d3129a4d580":{
      "scriptId":"u80"},
    "0b20dc27c96c432aafb14b024f58f503":{
      "scriptId":"u81"},
    "a0e4c5d9d610424dbfd4fa31683afe13":{
      "scriptId":"u82"},
    "7348216555af4de4ac1e6d92d483efe9":{
      "scriptId":"u83"},
    "14be4af3915f4d709b068957b275589b":{
      "scriptId":"u84"},
    "db927e6d9c1042198c0cd54e6e65fc23":{
      "scriptId":"u85"},
    "d7892495d36845f5a1337029e7f6ece4":{
      "scriptId":"u86"},
    "03bfbe5f778040d383a8e7cf1dd322a3":{
      "scriptId":"u87"},
    "b1f1e3cfaf864f8187d4f6bebf2f86b8":{
      "scriptId":"u88"},
    "ad4c5d9ef50644deb60556da3b6c7a62":{
      "scriptId":"u89"},
    "40d72e8ed1bf4ec7820da4e8e5b3cf6b":{
      "scriptId":"u90"},
    "84dff80a80924a07a39df558bebf6eec":{
      "scriptId":"u91"},
    "ba7f7f28610844f7aef2677d4d014e16":{
      "scriptId":"u92"},
    "08c171601c8b4627bc1e17a2a776a6b9":{
      "scriptId":"u93"},
    "c7f967a6d6ad40719724931be719df91":{
      "scriptId":"u94"}}});