$axure.loadCurrentPage({
  "url":"оплата.html",
  "generationDate":new Date(1423585592281.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f24b17c789484c5480cbe45e8e643332",
    "type":"Axure:Page",
    "name":"Оплата",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"98e0fd3c5d2d4e769a3a26cfaf2a42d6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":11}},
          "adaptiveStyles":{
},
          "masterId":"3c2651543160467bb6dbd1c6e4fb5ae6"},
{
          "id":"c67c5c2ea1bb4ee282b1da794468bc5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":218},
            "size":{
              "width":1280,
              "height":755}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a51a08e00f46405ab6eca4c3663b55d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":218},
                "size":{
                  "width":1280,
                  "height":755}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u36.png"}},
{
          "id":"216f324fc99047b2b1547cf8792b886b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":388},
            "size":{
              "width":1280,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec4a3e30880f40ac882f81d7307d73d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":388},
                "size":{
                  "width":1280,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u38.png"}},
{
          "id":"67078ad5143d43aeb8adc384112068c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":415},
            "size":{
              "width":374,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c16ed6a36ec047559f8d2955003bd3f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":415},
                "size":{
                  "width":374,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12403fb382cd4cac9eb3e3e8e77ab1a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":484},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0bf776002684a06af2eb64cfef86ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":484},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u42.png"}},
{
          "id":"bb989b0b6e584d8fa8b07c3b0f7bda94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":584},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e0e5597f1fe4b5a8f5ca04edd1ea55a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":584},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u42.png"}},
{
          "id":"002764ec30694105b3a14f96b22406c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":684},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4282fb4fdcc41f98faf1639180180e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":684},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u42.png"}},
{
          "id":"ead65d84ceb543f2bf684382e2ed72bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":484},
            "size":{
              "width":640,
              "height":489}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6254577c85a6433298c72fc8bdb1875b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":484},
                "size":{
                  "width":640,
                  "height":489}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u48.png"}},
{
          "id":"4cdee4caf61942a2954dc6d4ba9a9e1e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":499},
            "size":{
              "width":427,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"174c0bbf809844bca066a4ee17f373cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":499},
                "size":{
                  "width":427,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u50.png"}},
{
          "id":"dbc7ae86996c4d23877e15d27bfd402f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":584},
            "size":{
              "width":450,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac0146bbc5da48f7b50aa26105fcc2ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":584},
                "size":{
                  "width":450,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u52.png"}},
{
          "id":"45f6c3065dfc4f1c94139d9b1ddae248",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":706},
            "size":{
              "width":319,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e070cccecaa44f42802cf42e1232a657",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":706},
                "size":{
                  "width":319,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u54.png"}},
{
          "id":"4afc5da6f7b749ec9375bfafa00bd99b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":526},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f49363b82c9844509f78af0c536b8fc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":526},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c744b8ee77e34b0195a751e73e012cd3",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":626},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5394079ba1ee49159d1d749f80bf6967",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":626},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fc49b3f5e7eb4c9daa4171e692c03c5b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":726},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf5a4db3554541febaf2627c6f2d7fae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":726},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9e7b6e06d62a4fb69b84852c19618548",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":610},
            "size":{
              "width":220,
              "height":47}},
          "adaptiveStyles":{
}},
{
          "id":"a52538d425c5497e8a58590e619eca7c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":667},
            "size":{
              "width":350,
              "height":84}},
          "adaptiveStyles":{
}},
{
          "id":"99ec886502674e04907236b86a6bd488",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":800,
              "y":560},
            "size":{
              "width":210,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87fcdafce8fe4ecc903cef764c54a833",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":800,
                  "y":560},
                "size":{
                  "width":210,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4edbde0356c54823971b0aef97c8ac1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":768},
            "size":{
              "width":191,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bca145eeb7ce4d18a62003fa11598f43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":880,
                  "y":768},
                "size":{
                  "width":191,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u66.png"}},
{
          "id":"f4ad88b7924c4bcd843c582c10c7d539",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1030,
              "y":610},
            "size":{
              "width":120,
              "height":47}},
          "adaptiveStyles":{
}},
{
          "id":"9f01f522d0a84aca93ce7d8accb913e3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":973}},
          "adaptiveStyles":{
},
          "masterId":"1c043ff96f1947a9b4613e78a73b6b0b"},
{
          "id":"666db9fb357a48249bdb7f2eee01d901",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":244},
            "size":{
              "width":124,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0a560ecc5ff42b9a2741e9345d85662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":244},
                "size":{
                  "width":124,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u92.png"}},
{
          "id":"950ea78df9814536932ab7e26d4da2a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":144,
              "y":264},
            "size":{
              "width":460,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a257eea778444148add10769b5d23bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":144,
                  "y":264},
                "size":{
                  "width":460,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90071a0cbc5b4b74bded4c7e0b612fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":784},
            "size":{
              "width":640,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d53573a2f814e428cd2fdf925f1959b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":784},
                "size":{
                  "width":640,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u42.png"}},
{
          "id":"5fe0a3ed42664b359f60130acc56e124",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":826},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf808112248644d7a7a4bc866f55fe6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":826},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4ee64eb2ea4845239c6fff8bb9da009e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"700",
            "location":{
              "x":108,
              "y":821},
            "size":{
              "width":71,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05691b4afeb847a49b95ba9a3545c26d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"700",
                "location":{
                  "x":108,
                  "y":821},
                "size":{
                  "width":71,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13652b2b1a6949658ad451e8541ad918",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":920},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ad07546e49b491fb51eb716b536b0bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":920},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d664b2ebc55649429a8dc6c27ef55c13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"700",
            "location":{
              "x":108,
              "y":915},
            "size":{
              "width":526,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1788e3b086d94d7b9ff3aea742a16b8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"700",
                "location":{
                  "x":108,
                  "y":915},
                "size":{
                  "width":526,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce0403dc10d44400b1bfc6c43bb7de16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":849},
            "size":{
              "width":603,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63feedfc2f984370a4fcf3ad3716e697",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":674,
                  "y":849},
                "size":{
                  "width":603,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/оплата/u106.png"}}]}},
  "masters":{
    "3c2651543160467bb6dbd1c6e4fb5ae6":{
      "packageId":"3c2651543160467bb6dbd1c6e4fb5ae6",
      "type":"Axure:Master",
      "name":"Хидер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a24d26dd8cbf4f848f51c061f19d3ec2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-30},
              "size":{
                "width":1280,
                "height":207}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad4a5933465143999cd6214d999692d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-30},
                  "size":{
                    "width":1280,
                    "height":207}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"1986c1faae294ce5b785ebea9c9954d1",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":109},
              "size":{
                "width":950,
                "height":68}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b476c7edf27f4f47a1e333f7f8061d5e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":950,
                    "height":68}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2008e102df584d74a483975847661c17",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"824e543911104969870ab12502c80eda",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"b51e264b43464b27af113cbf070b274d",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":190,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0e31ad92b7bc4eeb941d4fc5633165db",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":190,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Категорія in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"категорія.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"94faf73cf2a140e1b5a65136362028b0",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":380,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"24f6277a43d84fe58c2bcc94f1624738",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":380,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"41195ca2d4eb4b25b02f328962a88fea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":570,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"262376ede03e425c805a7ee916d5dc4d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":570,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"774d22def07f4b3b92beaf7d3113c8e3",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":760,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f3ade7596611440d93de5a3f4d363b75",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":760,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u17.png"}}]}]},
{
            "id":"0f0ce908cb5e4e668e2051a152a009ac",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":-28.5},
              "size":{
                "width":480,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a3eac7c066243798a5b2c6235b26a0e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":-28.5},
                  "size":{
                    "width":480,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"63bef173bd0141fc9010fbfe0fd9b35c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "location":{
                "x":1114,
                "y":56},
              "size":{
                "width":107,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"310aa94f3d31441c9e33bfd9c9646e91",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "location":{
                    "x":1114,
                    "y":56},
                  "size":{
                    "width":107,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Про нас in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"про_нас.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"00fdbbc6f18a432fb754444bec683a49",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1207,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2d93413044cbfac754e65e456484a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1207,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u23.png"}},
{
            "id":"2b5505a026064198ae5312894c44877b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1165,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb4c16b29de94517bf081a61ec087285",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1165,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u25.png"}},
{
            "id":"1b1cbe0241714a378a81b178b0e86735",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1123,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c8fefe866140448f1e15b946398de4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1123,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fbe7887b2aad40989761f1b43212d52b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1081,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4cd45276529f4bfcb293119e311b3986",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1081,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"db9085386ae0403b872a52d3388be44d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":12,
                "y":8},
              "size":{
                "width":318,
                "height":57}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c72d5500e5974604a2afbae40f0bcab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":12,
                    "y":8},
                  "size":{
                    "width":318,
                    "height":57}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f6f939892ba64f94b76ad834e47d4b82",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":16,
                "y":64},
              "size":{
                "width":304,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"edfd1d481b144801bf684f564d0f14e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":16,
                    "y":64},
                  "size":{
                    "width":304,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb0d2181a3c346fda67248f2169af96c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":16,
                "y":-9},
              "size":{
                "width":108,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"01f1ed0e703140aaac8556b31d9fdc11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":-9},
                  "size":{
                    "width":108,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"885685ceb66b434e863ffd0845fa2b42",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1094,
                "y":54},
              "size":{
                "width":10,
                "height":32}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u37_line.png"}},
{
            "id":"82b50fcf1e0e409d9a5a12e93a7f8f67",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "location":{
                "x":980,
                "y":56},
              "size":{
                "width":104,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b12036b93c294313a4203a7ee8ea1f7c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "location":{
                    "x":980,
                    "y":56},
                  "size":{
                    "width":104,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Новини in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"новини.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "1c043ff96f1947a9b4613e78a73b6b0b":{
      "packageId":"1c043ff96f1947a9b4613e78a73b6b0b",
      "type":"Axure:Master",
      "name":"Футер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9fc91ae066174b309c3f0d46fe8888fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-10,
                "y":0},
              "size":{
                "width":1280,
                "height":300}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"66be155d52ee42588ea72dbc1f055f90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-10,
                    "y":0},
                  "size":{
                    "width":1280,
                    "height":300}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}},
{
            "id":"ddea022546f74b6fa41947b0291e2334",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":30,
                "y":14},
              "size":{
                "width":101,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89f2e4dfdcaf410fa5ba9dd499dc91b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":30,
                    "y":14},
                  "size":{
                    "width":101,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f5eb2795b014e089f2a0a4dcc667061",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":53},
              "size":{
                "width":70,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"763500db2a414e9e8c8b8a14e1d09b1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":53},
                  "size":{
                    "width":70,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b333f7fb5b88469b8dd4f8a599b79e6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":85},
              "size":{
                "width":68,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a84e81a6f8fd42b0a235a0ddca308e2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":85},
                  "size":{
                    "width":68,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"eda8c6e1c5184795bf3b637a1369fe9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":117},
              "size":{
                "width":64,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19eb2d053ee740da8b420086cb0ed542",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":117},
                  "size":{
                    "width":64,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bd067fad9b9d48deb6e6c41eb0492c8a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":332,
                "y":14},
              "size":{
                "width":111,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fcdd4cbfa904ec8aeac78a1a733ad40",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":332,
                    "y":14},
                  "size":{
                    "width":111,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce3bd7deeed248f89cf82ca82eeeed3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":332,
                "y":50},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92f32b9871b54ea6a20d2ecc7241d883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":332,
                    "y":50},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"11ad65cd45e84f4b95f147f21f1657c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":680,
                "y":14},
              "size":{
                "width":98,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93173ecf7ca04258870af0834f832b53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":680,
                    "y":14},
                  "size":{
                    "width":98,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e024c2b6a9384da7b6c1c8db894e3fd0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":50},
              "size":{
                "width":153,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80655206f5704739b7a76c9bd5754d26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":50},
                  "size":{
                    "width":153,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6d49b834c588458686a066d938e026be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":989,
                "y":14},
              "size":{
                "width":167,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe5fbb369ebb4ac8b1ee950406136e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":989,
                    "y":14},
                  "size":{
                    "width":167,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f663051151124546aa320df44882e86a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":989.000061035156,
                "y":50},
              "size":{
                "width":221,
                "height":220}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d76f835091e4469ea3d2706eb50c48ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":989.000061035156,
                    "y":50},
                  "size":{
                    "width":221,
                    "height":220}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u61.jpg"}}]}}},
  "objectPaths":{
    "98e0fd3c5d2d4e769a3a26cfaf2a42d6":{
      "scriptId":"u0",
      "a24d26dd8cbf4f848f51c061f19d3ec2":{
        "scriptId":"u1"},
      "ad4a5933465143999cd6214d999692d6":{
        "scriptId":"u2"},
      "1986c1faae294ce5b785ebea9c9954d1":{
        "scriptId":"u3"},
      "b476c7edf27f4f47a1e333f7f8061d5e":{
        "scriptId":"u4"},
      "2008e102df584d74a483975847661c17":{
        "scriptId":"u5"},
      "824e543911104969870ab12502c80eda":{
        "scriptId":"u6"},
      "b51e264b43464b27af113cbf070b274d":{
        "scriptId":"u7"},
      "0e31ad92b7bc4eeb941d4fc5633165db":{
        "scriptId":"u8"},
      "94faf73cf2a140e1b5a65136362028b0":{
        "scriptId":"u9"},
      "24f6277a43d84fe58c2bcc94f1624738":{
        "scriptId":"u10"},
      "41195ca2d4eb4b25b02f328962a88fea":{
        "scriptId":"u11"},
      "262376ede03e425c805a7ee916d5dc4d":{
        "scriptId":"u12"},
      "774d22def07f4b3b92beaf7d3113c8e3":{
        "scriptId":"u13"},
      "f3ade7596611440d93de5a3f4d363b75":{
        "scriptId":"u14"},
      "0f0ce908cb5e4e668e2051a152a009ac":{
        "scriptId":"u15"},
      "8a3eac7c066243798a5b2c6235b26a0e":{
        "scriptId":"u16"},
      "63bef173bd0141fc9010fbfe0fd9b35c":{
        "scriptId":"u17"},
      "310aa94f3d31441c9e33bfd9c9646e91":{
        "scriptId":"u18"},
      "00fdbbc6f18a432fb754444bec683a49":{
        "scriptId":"u19"},
      "cdf2d93413044cbfac754e65e456484a":{
        "scriptId":"u20"},
      "2b5505a026064198ae5312894c44877b":{
        "scriptId":"u21"},
      "bb4c16b29de94517bf081a61ec087285":{
        "scriptId":"u22"},
      "1b1cbe0241714a378a81b178b0e86735":{
        "scriptId":"u23"},
      "68c8fefe866140448f1e15b946398de4":{
        "scriptId":"u24"},
      "fbe7887b2aad40989761f1b43212d52b":{
        "scriptId":"u25"},
      "4cd45276529f4bfcb293119e311b3986":{
        "scriptId":"u26"},
      "db9085386ae0403b872a52d3388be44d":{
        "scriptId":"u27"},
      "c72d5500e5974604a2afbae40f0bcab2":{
        "scriptId":"u28"},
      "f6f939892ba64f94b76ad834e47d4b82":{
        "scriptId":"u29"},
      "edfd1d481b144801bf684f564d0f14e2":{
        "scriptId":"u30"},
      "bb0d2181a3c346fda67248f2169af96c":{
        "scriptId":"u31"},
      "01f1ed0e703140aaac8556b31d9fdc11":{
        "scriptId":"u32"},
      "885685ceb66b434e863ffd0845fa2b42":{
        "scriptId":"u33"},
      "82b50fcf1e0e409d9a5a12e93a7f8f67":{
        "scriptId":"u34"},
      "b12036b93c294313a4203a7ee8ea1f7c":{
        "scriptId":"u35"}},
    "c67c5c2ea1bb4ee282b1da794468bc5f":{
      "scriptId":"u36"},
    "a51a08e00f46405ab6eca4c3663b55d1":{
      "scriptId":"u37"},
    "216f324fc99047b2b1547cf8792b886b":{
      "scriptId":"u38"},
    "ec4a3e30880f40ac882f81d7307d73d3":{
      "scriptId":"u39"},
    "67078ad5143d43aeb8adc384112068c0":{
      "scriptId":"u40"},
    "c16ed6a36ec047559f8d2955003bd3f4":{
      "scriptId":"u41"},
    "12403fb382cd4cac9eb3e3e8e77ab1a0":{
      "scriptId":"u42"},
    "f0bf776002684a06af2eb64cfef86ca9":{
      "scriptId":"u43"},
    "bb989b0b6e584d8fa8b07c3b0f7bda94":{
      "scriptId":"u44"},
    "9e0e5597f1fe4b5a8f5ca04edd1ea55a":{
      "scriptId":"u45"},
    "002764ec30694105b3a14f96b22406c8":{
      "scriptId":"u46"},
    "a4282fb4fdcc41f98faf1639180180e6":{
      "scriptId":"u47"},
    "ead65d84ceb543f2bf684382e2ed72bf":{
      "scriptId":"u48"},
    "6254577c85a6433298c72fc8bdb1875b":{
      "scriptId":"u49"},
    "4cdee4caf61942a2954dc6d4ba9a9e1e":{
      "scriptId":"u50"},
    "174c0bbf809844bca066a4ee17f373cd":{
      "scriptId":"u51"},
    "dbc7ae86996c4d23877e15d27bfd402f":{
      "scriptId":"u52"},
    "ac0146bbc5da48f7b50aa26105fcc2ab":{
      "scriptId":"u53"},
    "45f6c3065dfc4f1c94139d9b1ddae248":{
      "scriptId":"u54"},
    "e070cccecaa44f42802cf42e1232a657":{
      "scriptId":"u55"},
    "4afc5da6f7b749ec9375bfafa00bd99b":{
      "scriptId":"u56"},
    "f49363b82c9844509f78af0c536b8fc0":{
      "scriptId":"u57"},
    "c744b8ee77e34b0195a751e73e012cd3":{
      "scriptId":"u58"},
    "5394079ba1ee49159d1d749f80bf6967":{
      "scriptId":"u59"},
    "fc49b3f5e7eb4c9daa4171e692c03c5b":{
      "scriptId":"u60"},
    "cf5a4db3554541febaf2627c6f2d7fae":{
      "scriptId":"u61"},
    "9e7b6e06d62a4fb69b84852c19618548":{
      "scriptId":"u62"},
    "a52538d425c5497e8a58590e619eca7c":{
      "scriptId":"u63"},
    "99ec886502674e04907236b86a6bd488":{
      "scriptId":"u64"},
    "87fcdafce8fe4ecc903cef764c54a833":{
      "scriptId":"u65"},
    "4edbde0356c54823971b0aef97c8ac1f":{
      "scriptId":"u66"},
    "bca145eeb7ce4d18a62003fa11598f43":{
      "scriptId":"u67"},
    "f4ad88b7924c4bcd843c582c10c7d539":{
      "scriptId":"u68"},
    "9f01f522d0a84aca93ce7d8accb913e3":{
      "scriptId":"u69",
      "9fc91ae066174b309c3f0d46fe8888fb":{
        "scriptId":"u70"},
      "66be155d52ee42588ea72dbc1f055f90":{
        "scriptId":"u71"},
      "ddea022546f74b6fa41947b0291e2334":{
        "scriptId":"u72"},
      "89f2e4dfdcaf410fa5ba9dd499dc91b8":{
        "scriptId":"u73"},
      "9f5eb2795b014e089f2a0a4dcc667061":{
        "scriptId":"u74"},
      "763500db2a414e9e8c8b8a14e1d09b1a":{
        "scriptId":"u75"},
      "b333f7fb5b88469b8dd4f8a599b79e6a":{
        "scriptId":"u76"},
      "a84e81a6f8fd42b0a235a0ddca308e2a":{
        "scriptId":"u77"},
      "eda8c6e1c5184795bf3b637a1369fe9d":{
        "scriptId":"u78"},
      "19eb2d053ee740da8b420086cb0ed542":{
        "scriptId":"u79"},
      "bd067fad9b9d48deb6e6c41eb0492c8a":{
        "scriptId":"u80"},
      "5fcdd4cbfa904ec8aeac78a1a733ad40":{
        "scriptId":"u81"},
      "ce3bd7deeed248f89cf82ca82eeeed3f":{
        "scriptId":"u82"},
      "92f32b9871b54ea6a20d2ecc7241d883":{
        "scriptId":"u83"},
      "11ad65cd45e84f4b95f147f21f1657c2":{
        "scriptId":"u84"},
      "93173ecf7ca04258870af0834f832b53":{
        "scriptId":"u85"},
      "e024c2b6a9384da7b6c1c8db894e3fd0":{
        "scriptId":"u86"},
      "80655206f5704739b7a76c9bd5754d26":{
        "scriptId":"u87"},
      "6d49b834c588458686a066d938e026be":{
        "scriptId":"u88"},
      "fe5fbb369ebb4ac8b1ee950406136e69":{
        "scriptId":"u89"},
      "f663051151124546aa320df44882e86a":{
        "scriptId":"u90"},
      "d76f835091e4469ea3d2706eb50c48ae":{
        "scriptId":"u91"}},
    "666db9fb357a48249bdb7f2eee01d901":{
      "scriptId":"u92"},
    "e0a560ecc5ff42b9a2741e9345d85662":{
      "scriptId":"u93"},
    "950ea78df9814536932ab7e26d4da2a7":{
      "scriptId":"u94"},
    "a257eea778444148add10769b5d23bdf":{
      "scriptId":"u95"},
    "90071a0cbc5b4b74bded4c7e0b612fad":{
      "scriptId":"u96"},
    "1d53573a2f814e428cd2fdf925f1959b":{
      "scriptId":"u97"},
    "5fe0a3ed42664b359f60130acc56e124":{
      "scriptId":"u98"},
    "bf808112248644d7a7a4bc866f55fe6e":{
      "scriptId":"u99"},
    "4ee64eb2ea4845239c6fff8bb9da009e":{
      "scriptId":"u100"},
    "05691b4afeb847a49b95ba9a3545c26d":{
      "scriptId":"u101"},
    "13652b2b1a6949658ad451e8541ad918":{
      "scriptId":"u102"},
    "1ad07546e49b491fb51eb716b536b0bf":{
      "scriptId":"u103"},
    "d664b2ebc55649429a8dc6c27ef55c13":{
      "scriptId":"u104"},
    "1788e3b086d94d7b9ff3aea742a16b8e":{
      "scriptId":"u105"},
    "ce0403dc10d44400b1bfc6c43bb7de16":{
      "scriptId":"u106"},
    "63feedfc2f984370a4fcf3ad3716e697":{
      "scriptId":"u107"}}});