$axure.loadCurrentPage({
  "url":"_recomend_1.html",
  "generationDate":new Date(1426468453267.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"63dbe93ba3c746919380db96eba2ed3c",
    "type":"Axure:Page",
    "name":"!Recomend_1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2764d915d2954a20af6505bb6bd9c17c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"3c2651543160467bb6dbd1c6e4fb5ae6"},
{
          "id":"6782dcee0eee4d9aae32feab306ccb17",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":850}},
          "adaptiveStyles":{
},
          "masterId":"1c043ff96f1947a9b4613e78a73b6b0b"},
{
          "id":"b057de6b84c74dde9379ff9099ba1915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"32px",
            "fontWeight":"700",
            "location":{
              "x":490,
              "y":229},
            "size":{
              "width":295,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"351df471960d4dee8798b4af21f5fd2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"32px",
                "fontWeight":"700",
                "location":{
                  "x":490,
                  "y":229},
                "size":{
                  "width":295,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0009af792fc49a0a38d51ad86283bd0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":294},
            "size":{
              "width":166,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63f0f1e85f70479ca32d48ece54eaefb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":294},
                "size":{
                  "width":166,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_recomend_1/u80.png"}},
{
          "id":"5a216667563a493f98a18e63a95feaf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":192,
              "y":294},
            "size":{
              "width":128,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99e3cd3dd8564e51b9591411b73be04f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":192,
                  "y":294},
                "size":{
                  "width":128,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95c321de4bd440b3b3a342be03c8af06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":192,
              "y":337},
            "size":{
              "width":228,
              "height":138}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71760e72d62f4f6c93b2285a66004341",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":192,
                  "y":337},
                "size":{
                  "width":228,
                  "height":138}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab4d0f904ea14a4789369d8dcacbdce3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":862,
              "y":294},
            "size":{
              "width":166,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6efefb9313434dfc825c6bff940e7f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":862,
                  "y":294},
                "size":{
                  "width":166,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_recomend_1/u80.png"}},
{
          "id":"6a9daaca7a4e41da9f085a80518aae51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1036,
              "y":294},
            "size":{
              "width":128,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f88bc1cf4c741cf9f2451ad0e54bf8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1036,
                  "y":294},
                "size":{
                  "width":128,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d398f3aed7734d40b940d2e6f42015c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1036,
              "y":337},
            "size":{
              "width":228,
              "height":138}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00dfb79b386a46298389bc683d97f26c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1036,
                  "y":337},
                "size":{
                  "width":228,
                  "height":138}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bf7bb3bbce64a14b81b7bd4239a780b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":294},
            "size":{
              "width":166,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65c1b3972ee942778efbc6fff6e56861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":294},
                "size":{
                  "width":166,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_recomend_1/u80.png"}},
{
          "id":"1f1d15ac32c245b49b1f88b6b1a1ccb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":604,
              "y":294},
            "size":{
              "width":128,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22f075f00f5e4336b1a2815d77808699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":604,
                  "y":294},
                "size":{
                  "width":128,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9270ac828e914ecd94d92d933507e1fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":337},
            "size":{
              "width":228,
              "height":138}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84b26ce1e26545c183da15bb44187d59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":337},
                "size":{
                  "width":228,
                  "height":138}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"747b40b128504facb8807ad95b599be1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":518},
            "size":{
              "width":166,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"489dda3d9d1444b6bc5908c3eda7dee6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":518},
                "size":{
                  "width":166,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_recomend_1/u80.png"}},
{
          "id":"7746468acd4a4cd38b533f39eed44601",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":190,
              "y":518},
            "size":{
              "width":128,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0cab72dd2384391813ac51a20527d05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":190,
                  "y":518},
                "size":{
                  "width":128,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"609ae63f252d4ec9b1a35a25aa653f3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":561},
            "size":{
              "width":228,
              "height":138}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"306da7f17bf543868d416cd63ebd5394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":561},
                "size":{
                  "width":228,
                  "height":138}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28efa53f9d8745a59441b804177dcf3d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":518},
            "size":{
              "width":166,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3f6d6a8ba5246ffa4750141bd25392e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":860,
                  "y":518},
                "size":{
                  "width":166,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_recomend_1/u80.png"}},
{
          "id":"0642b5002601453782b5bd830941e056",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1034,
              "y":518},
            "size":{
              "width":128,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05423b9ed1a24f429840877fceade6d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1034,
                  "y":518},
                "size":{
                  "width":128,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"392e1b979b75415886b61a202f045893",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1034,
              "y":561},
            "size":{
              "width":228,
              "height":138}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d460e6218ac48ecbb7eaaffb27fe56b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1034,
                  "y":561},
                "size":{
                  "width":228,
                  "height":138}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e52c67fb58944f3ea23e6cc5d2e8c2b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":518},
            "size":{
              "width":166,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d96dc8b1d4ee411c96fc8416bf820b7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":518},
                "size":{
                  "width":166,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_recomend_1/u80.png"}},
{
          "id":"4048de38884d46f8a7dbfb34c9b91183",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":602,
              "y":518},
            "size":{
              "width":128,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42cbe4d1c70b4c569ba3eaac5bd3ac4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":602,
                  "y":518},
                "size":{
                  "width":128,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27ba7bbccebf4c948cb22f92834c0f44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":602,
              "y":561},
            "size":{
              "width":228,
              "height":138}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e64a5894e1440d7ab302830e6286fb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":602,
                  "y":561},
                "size":{
                  "width":228,
                  "height":138}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "3c2651543160467bb6dbd1c6e4fb5ae6":{
      "packageId":"3c2651543160467bb6dbd1c6e4fb5ae6",
      "type":"Axure:Master",
      "name":"Хидер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a24d26dd8cbf4f848f51c061f19d3ec2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-30},
              "size":{
                "width":1280,
                "height":207}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad4a5933465143999cd6214d999692d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-30},
                  "size":{
                    "width":1280,
                    "height":207}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.png"}},
{
            "id":"1986c1faae294ce5b785ebea9c9954d1",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":109},
              "size":{
                "width":1280,
                "height":68}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b476c7edf27f4f47a1e333f7f8061d5e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":1280,
                    "height":68}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2008e102df584d74a483975847661c17",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"824e543911104969870ab12502c80eda",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u5.png"}},
{
                    "id":"b51e264b43464b27af113cbf070b274d",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":183,
                        "y":0},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0e31ad92b7bc4eeb941d4fc5633165db",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":183,
                            "y":0},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open !All Projects in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"_all_projects.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u5.png"}},
{
                    "id":"94faf73cf2a140e1b5a65136362028b0",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":366,
                        "y":0},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"24f6277a43d84fe58c2bcc94f1624738",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":366,
                            "y":0},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open !Buisness in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"_buisness.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u5.png"}},
{
                    "id":"41195ca2d4eb4b25b02f328962a88fea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":549,
                        "y":0},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"262376ede03e425c805a7ee916d5dc4d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":549,
                            "y":0},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open !Diaspora in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"_diaspora.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u5.png"}},
{
                    "id":"774d22def07f4b3b92beaf7d3113c8e3",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":732,
                        "y":0},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f3ade7596611440d93de5a3f4d363b75",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":732,
                            "y":0},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u5.png"}},
{
                    "id":"24db02bcbff8461cbea21ec682c852e4",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":1098,
                        "y":0},
                      "size":{
                        "width":182,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c477273f7bd4c68b1992c1e467819a1",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":1098,
                            "y":0},
                          "size":{
                            "width":182,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open !About in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"_about.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u17.png"}},
{
                    "id":"9bba04f51c5e482eab48c197c0c5363f",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":915,
                        "y":0},
                      "size":{
                        "width":183,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"782008b02e71410c967b33d141b84e61",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":915,
                            "y":0},
                          "size":{
                            "width":183,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open !News in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"_news.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u5.png"}}]},
{
                "id":"9ac348a26857416bb79680212145b5ee",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":732,
                    "y":68},
                  "size":{
                    "width":183,
                    "height":184},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"57f74f87cb2b4977906ae56b1eff6a24",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":183,
                        "height":184}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aa6e42cab61645a796d2e7097ab11d74",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":183,
                            "height":52},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"77b18f4acbcf48d1859ab4ad0c890f59",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"20px",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "size":{
                                "width":183,
                                "height":52},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"Case 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"Open !Recomend_1 in Current Window",
                                    "target":{
                                      "targetType":"page",
                                      "url":"_recomend_1.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/home/u21.png"}},
{
                        "id":"d95218d3a5894504a44fad0c51d22001",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":52},
                          "size":{
                            "width":183,
                            "height":28},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"ca77b8d2026844908ce20fb529f62b75",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"20px",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":52},
                              "size":{
                                "width":183,
                                "height":28},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/home/u23.png"}},
{
                        "id":"7099eefa6fba4881af72c12718122013",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":80},
                          "size":{
                            "width":183,
                            "height":52},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"9aa0b348d01d48f3b73caddff9a4c394",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"20px",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":80},
                              "size":{
                                "width":183,
                                "height":52},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/home/u21.png"}},
{
                        "id":"56e892457d674da3b1c1698007cb7ef0",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":132},
                          "size":{
                            "width":183,
                            "height":52},
                          "limbo":false},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"2c778d6550b644c486976c478a7d72e5",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"20px",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFF},
                              "location":{
                                "x":0,
                                "y":132},
                              "size":{
                                "width":183,
                                "height":52},
                              "limbo":false},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/home/u27.png"}}]}],
                "parentCellId":"774d22def07f4b3b92beaf7d3113c8e3"}]},
{
            "id":"0f0ce908cb5e4e668e2051a152a009ac",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":-28},
              "size":{
                "width":580,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a3eac7c066243798a5b2c6235b26a0e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":-28},
                  "size":{
                    "width":580,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u29.jpg"}},
{
            "id":"00fdbbc6f18a432fb754444bec683a49",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1207,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2d93413044cbfac754e65e456484a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1207,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u31.png"}},
{
            "id":"2b5505a026064198ae5312894c44877b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1165,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb4c16b29de94517bf081a61ec087285",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1165,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u33.png"}},
{
            "id":"1b1cbe0241714a378a81b178b0e86735",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1123,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c8fefe866140448f1e15b946398de4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1123,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u35.png"}},
{
            "id":"fbe7887b2aad40989761f1b43212d52b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1081,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4cd45276529f4bfcb293119e311b3986",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1081,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u37.png"}},
{
            "id":"db9085386ae0403b872a52d3388be44d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":12,
                "y":8},
              "size":{
                "width":318,
                "height":57}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c72d5500e5974604a2afbae40f0bcab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":12,
                    "y":8},
                  "size":{
                    "width":318,
                    "height":57}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f6f939892ba64f94b76ad834e47d4b82",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":16,
                "y":64},
              "size":{
                "width":304,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"edfd1d481b144801bf684f564d0f14e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":16,
                    "y":64},
                  "size":{
                    "width":304,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb0d2181a3c346fda67248f2169af96c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":16,
                "y":-9},
              "size":{
                "width":108,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"01f1ed0e703140aaac8556b31d9fdc11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":-9},
                  "size":{
                    "width":108,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"48be34192e0a4fa5925bc7074e0e92f1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"22px",
              "location":{
                "x":1006,
                "y":-7},
              "size":{
                "width":44,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"373f4e85b54046ab84cbd7d14d4188ce",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"22px",
                  "location":{
                    "x":1006,
                    "y":-7},
                  "size":{
                    "width":44,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "1c043ff96f1947a9b4613e78a73b6b0b":{
      "packageId":"1c043ff96f1947a9b4613e78a73b6b0b",
      "type":"Axure:Master",
      "name":"Футер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9fc91ae066174b309c3f0d46fe8888fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-10,
                "y":0},
              "size":{
                "width":1280,
                "height":300}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"66be155d52ee42588ea72dbc1f055f90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-10,
                    "y":0},
                  "size":{
                    "width":1280,
                    "height":300}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u48.png"}},
{
            "id":"ddea022546f74b6fa41947b0291e2334",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":30,
                "y":14},
              "size":{
                "width":101,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89f2e4dfdcaf410fa5ba9dd499dc91b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":30,
                    "y":14},
                  "size":{
                    "width":101,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f5eb2795b014e089f2a0a4dcc667061",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":53},
              "size":{
                "width":70,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"763500db2a414e9e8c8b8a14e1d09b1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":53},
                  "size":{
                    "width":70,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b333f7fb5b88469b8dd4f8a599b79e6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":85},
              "size":{
                "width":68,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a84e81a6f8fd42b0a235a0ddca308e2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":85},
                  "size":{
                    "width":68,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"eda8c6e1c5184795bf3b637a1369fe9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":117},
              "size":{
                "width":64,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19eb2d053ee740da8b420086cb0ed542",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":117},
                  "size":{
                    "width":64,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bd067fad9b9d48deb6e6c41eb0492c8a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":332,
                "y":14},
              "size":{
                "width":160,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fcdd4cbfa904ec8aeac78a1a733ad40",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":332,
                    "y":14},
                  "size":{
                    "width":160,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce3bd7deeed248f89cf82ca82eeeed3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":332,
                "y":50},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92f32b9871b54ea6a20d2ecc7241d883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":332,
                    "y":50},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"11ad65cd45e84f4b95f147f21f1657c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":680,
                "y":14},
              "size":{
                "width":98,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93173ecf7ca04258870af0834f832b53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":680,
                    "y":14},
                  "size":{
                    "width":98,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e024c2b6a9384da7b6c1c8db894e3fd0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":50},
              "size":{
                "width":153,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80655206f5704739b7a76c9bd5754d26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":50},
                  "size":{
                    "width":153,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6d49b834c588458686a066d938e026be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":989,
                "y":14},
              "size":{
                "width":167,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe5fbb369ebb4ac8b1ee950406136e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":989,
                    "y":14},
                  "size":{
                    "width":167,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f663051151124546aa320df44882e86a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":989.000061035156,
                "y":50},
              "size":{
                "width":221,
                "height":220}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d76f835091e4469ea3d2706eb50c48ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":989.000061035156,
                    "y":50},
                  "size":{
                    "width":221,
                    "height":220}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u68.jpg"}},
{
            "id":"1cf32189befe4fe2bff08a5095974b0f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":159},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48dfd1fc634a4d5383a086db0d2c2604",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":159},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u70.png"}},
{
            "id":"ffe38148cf74490888da731228dad2c3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":740,
                "y":176},
              "size":{
                "width":101,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"076390907da442c5873080a95cdaf7f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":740,
                    "y":176},
                  "size":{
                    "width":101,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ab7c9753ece44de0af0637a216188e24",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":219},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1aee3f32134c4be0848277842ea15268",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":219},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u70.png"}},
{
            "id":"bd903b22dcfb403aad7f42f835a7091e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":740,
                "y":236},
              "size":{
                "width":81,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ab6aa297e717408ab4bba582e7c999b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":740,
                    "y":236},
                  "size":{
                    "width":81,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "2764d915d2954a20af6505bb6bd9c17c":{
      "scriptId":"u0",
      "a24d26dd8cbf4f848f51c061f19d3ec2":{
        "scriptId":"u1"},
      "ad4a5933465143999cd6214d999692d6":{
        "scriptId":"u2"},
      "1986c1faae294ce5b785ebea9c9954d1":{
        "scriptId":"u3"},
      "b476c7edf27f4f47a1e333f7f8061d5e":{
        "scriptId":"u4"},
      "2008e102df584d74a483975847661c17":{
        "scriptId":"u5"},
      "824e543911104969870ab12502c80eda":{
        "scriptId":"u6"},
      "b51e264b43464b27af113cbf070b274d":{
        "scriptId":"u7"},
      "0e31ad92b7bc4eeb941d4fc5633165db":{
        "scriptId":"u8"},
      "94faf73cf2a140e1b5a65136362028b0":{
        "scriptId":"u9"},
      "24f6277a43d84fe58c2bcc94f1624738":{
        "scriptId":"u10"},
      "41195ca2d4eb4b25b02f328962a88fea":{
        "scriptId":"u11"},
      "262376ede03e425c805a7ee916d5dc4d":{
        "scriptId":"u12"},
      "774d22def07f4b3b92beaf7d3113c8e3":{
        "scriptId":"u13"},
      "f3ade7596611440d93de5a3f4d363b75":{
        "scriptId":"u14"},
      "9bba04f51c5e482eab48c197c0c5363f":{
        "scriptId":"u15"},
      "782008b02e71410c967b33d141b84e61":{
        "scriptId":"u16"},
      "24db02bcbff8461cbea21ec682c852e4":{
        "scriptId":"u17"},
      "1c477273f7bd4c68b1992c1e467819a1":{
        "scriptId":"u18"},
      "9ac348a26857416bb79680212145b5ee":{
        "scriptId":"u19"},
      "57f74f87cb2b4977906ae56b1eff6a24":{
        "scriptId":"u20"},
      "aa6e42cab61645a796d2e7097ab11d74":{
        "scriptId":"u21"},
      "77b18f4acbcf48d1859ab4ad0c890f59":{
        "scriptId":"u22"},
      "d95218d3a5894504a44fad0c51d22001":{
        "scriptId":"u23"},
      "ca77b8d2026844908ce20fb529f62b75":{
        "scriptId":"u24"},
      "7099eefa6fba4881af72c12718122013":{
        "scriptId":"u25"},
      "9aa0b348d01d48f3b73caddff9a4c394":{
        "scriptId":"u26"},
      "56e892457d674da3b1c1698007cb7ef0":{
        "scriptId":"u27"},
      "2c778d6550b644c486976c478a7d72e5":{
        "scriptId":"u28"},
      "0f0ce908cb5e4e668e2051a152a009ac":{
        "scriptId":"u29"},
      "8a3eac7c066243798a5b2c6235b26a0e":{
        "scriptId":"u30"},
      "00fdbbc6f18a432fb754444bec683a49":{
        "scriptId":"u31"},
      "cdf2d93413044cbfac754e65e456484a":{
        "scriptId":"u32"},
      "2b5505a026064198ae5312894c44877b":{
        "scriptId":"u33"},
      "bb4c16b29de94517bf081a61ec087285":{
        "scriptId":"u34"},
      "1b1cbe0241714a378a81b178b0e86735":{
        "scriptId":"u35"},
      "68c8fefe866140448f1e15b946398de4":{
        "scriptId":"u36"},
      "fbe7887b2aad40989761f1b43212d52b":{
        "scriptId":"u37"},
      "4cd45276529f4bfcb293119e311b3986":{
        "scriptId":"u38"},
      "db9085386ae0403b872a52d3388be44d":{
        "scriptId":"u39"},
      "c72d5500e5974604a2afbae40f0bcab2":{
        "scriptId":"u40"},
      "f6f939892ba64f94b76ad834e47d4b82":{
        "scriptId":"u41"},
      "edfd1d481b144801bf684f564d0f14e2":{
        "scriptId":"u42"},
      "bb0d2181a3c346fda67248f2169af96c":{
        "scriptId":"u43"},
      "01f1ed0e703140aaac8556b31d9fdc11":{
        "scriptId":"u44"},
      "48be34192e0a4fa5925bc7074e0e92f1":{
        "scriptId":"u45"},
      "373f4e85b54046ab84cbd7d14d4188ce":{
        "scriptId":"u46"}},
    "6782dcee0eee4d9aae32feab306ccb17":{
      "scriptId":"u47",
      "9fc91ae066174b309c3f0d46fe8888fb":{
        "scriptId":"u48"},
      "66be155d52ee42588ea72dbc1f055f90":{
        "scriptId":"u49"},
      "ddea022546f74b6fa41947b0291e2334":{
        "scriptId":"u50"},
      "89f2e4dfdcaf410fa5ba9dd499dc91b8":{
        "scriptId":"u51"},
      "9f5eb2795b014e089f2a0a4dcc667061":{
        "scriptId":"u52"},
      "763500db2a414e9e8c8b8a14e1d09b1a":{
        "scriptId":"u53"},
      "b333f7fb5b88469b8dd4f8a599b79e6a":{
        "scriptId":"u54"},
      "a84e81a6f8fd42b0a235a0ddca308e2a":{
        "scriptId":"u55"},
      "eda8c6e1c5184795bf3b637a1369fe9d":{
        "scriptId":"u56"},
      "19eb2d053ee740da8b420086cb0ed542":{
        "scriptId":"u57"},
      "bd067fad9b9d48deb6e6c41eb0492c8a":{
        "scriptId":"u58"},
      "5fcdd4cbfa904ec8aeac78a1a733ad40":{
        "scriptId":"u59"},
      "ce3bd7deeed248f89cf82ca82eeeed3f":{
        "scriptId":"u60"},
      "92f32b9871b54ea6a20d2ecc7241d883":{
        "scriptId":"u61"},
      "11ad65cd45e84f4b95f147f21f1657c2":{
        "scriptId":"u62"},
      "93173ecf7ca04258870af0834f832b53":{
        "scriptId":"u63"},
      "e024c2b6a9384da7b6c1c8db894e3fd0":{
        "scriptId":"u64"},
      "80655206f5704739b7a76c9bd5754d26":{
        "scriptId":"u65"},
      "6d49b834c588458686a066d938e026be":{
        "scriptId":"u66"},
      "fe5fbb369ebb4ac8b1ee950406136e69":{
        "scriptId":"u67"},
      "f663051151124546aa320df44882e86a":{
        "scriptId":"u68"},
      "d76f835091e4469ea3d2706eb50c48ae":{
        "scriptId":"u69"},
      "1cf32189befe4fe2bff08a5095974b0f":{
        "scriptId":"u70"},
      "48dfd1fc634a4d5383a086db0d2c2604":{
        "scriptId":"u71"},
      "ffe38148cf74490888da731228dad2c3":{
        "scriptId":"u72"},
      "076390907da442c5873080a95cdaf7f4":{
        "scriptId":"u73"},
      "ab7c9753ece44de0af0637a216188e24":{
        "scriptId":"u74"},
      "1aee3f32134c4be0848277842ea15268":{
        "scriptId":"u75"},
      "bd903b22dcfb403aad7f42f835a7091e":{
        "scriptId":"u76"},
      "ab6aa297e717408ab4bba582e7c999b8":{
        "scriptId":"u77"}},
    "b057de6b84c74dde9379ff9099ba1915":{
      "scriptId":"u78"},
    "351df471960d4dee8798b4af21f5fd2e":{
      "scriptId":"u79"},
    "f0009af792fc49a0a38d51ad86283bd0":{
      "scriptId":"u80"},
    "63f0f1e85f70479ca32d48ece54eaefb":{
      "scriptId":"u81"},
    "5a216667563a493f98a18e63a95feaf3":{
      "scriptId":"u82"},
    "99e3cd3dd8564e51b9591411b73be04f":{
      "scriptId":"u83"},
    "95c321de4bd440b3b3a342be03c8af06":{
      "scriptId":"u84"},
    "71760e72d62f4f6c93b2285a66004341":{
      "scriptId":"u85"},
    "ab4d0f904ea14a4789369d8dcacbdce3":{
      "scriptId":"u86"},
    "6efefb9313434dfc825c6bff940e7f31":{
      "scriptId":"u87"},
    "6a9daaca7a4e41da9f085a80518aae51":{
      "scriptId":"u88"},
    "7f88bc1cf4c741cf9f2451ad0e54bf8f":{
      "scriptId":"u89"},
    "d398f3aed7734d40b940d2e6f42015c1":{
      "scriptId":"u90"},
    "00dfb79b386a46298389bc683d97f26c":{
      "scriptId":"u91"},
    "4bf7bb3bbce64a14b81b7bd4239a780b":{
      "scriptId":"u92"},
    "65c1b3972ee942778efbc6fff6e56861":{
      "scriptId":"u93"},
    "1f1d15ac32c245b49b1f88b6b1a1ccb6":{
      "scriptId":"u94"},
    "22f075f00f5e4336b1a2815d77808699":{
      "scriptId":"u95"},
    "9270ac828e914ecd94d92d933507e1fc":{
      "scriptId":"u96"},
    "84b26ce1e26545c183da15bb44187d59":{
      "scriptId":"u97"},
    "747b40b128504facb8807ad95b599be1":{
      "scriptId":"u98"},
    "489dda3d9d1444b6bc5908c3eda7dee6":{
      "scriptId":"u99"},
    "7746468acd4a4cd38b533f39eed44601":{
      "scriptId":"u100"},
    "e0cab72dd2384391813ac51a20527d05":{
      "scriptId":"u101"},
    "609ae63f252d4ec9b1a35a25aa653f3b":{
      "scriptId":"u102"},
    "306da7f17bf543868d416cd63ebd5394":{
      "scriptId":"u103"},
    "28efa53f9d8745a59441b804177dcf3d":{
      "scriptId":"u104"},
    "c3f6d6a8ba5246ffa4750141bd25392e":{
      "scriptId":"u105"},
    "0642b5002601453782b5bd830941e056":{
      "scriptId":"u106"},
    "05423b9ed1a24f429840877fceade6d2":{
      "scriptId":"u107"},
    "392e1b979b75415886b61a202f045893":{
      "scriptId":"u108"},
    "8d460e6218ac48ecbb7eaaffb27fe56b":{
      "scriptId":"u109"},
    "e52c67fb58944f3ea23e6cc5d2e8c2b4":{
      "scriptId":"u110"},
    "d96dc8b1d4ee411c96fc8416bf820b7c":{
      "scriptId":"u111"},
    "4048de38884d46f8a7dbfb34c9b91183":{
      "scriptId":"u112"},
    "42cbe4d1c70b4c569ba3eaac5bd3ac4b":{
      "scriptId":"u113"},
    "27ba7bbccebf4c948cb22f92834c0f44":{
      "scriptId":"u114"},
    "3e64a5894e1440d7ab302830e6286fb7":{
      "scriptId":"u115"}}});