$axure.loadCurrentPage({
  "url":"category.html",
  "generationDate":new Date(1423593365126.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c3177c9ecd6949f3abab9be19d6adc45",
    "type":"Axure:Page",
    "name":"Category",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"573287fbecb241ffb2768c166453bcf5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":11}},
          "adaptiveStyles":{
},
          "masterId":"3c2651543160467bb6dbd1c6e4fb5ae6"},
{
          "id":"10486424da8b47ebbbb349543a5017cb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1420}},
          "adaptiveStyles":{
},
          "masterId":"1c043ff96f1947a9b4613e78a73b6b0b"},
{
          "id":"6326b92ef65a4232a35c096e1bb1f130",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":218},
            "size":{
              "width":1281,
              "height":1202}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b706e56b5f34570b89dedb2926e23ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":218},
                "size":{
                  "width":1281,
                  "height":1202}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u59.png"}},
{
          "id":"5ac7992d08374ac8b47fa25d4aa8a962",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":957},
            "size":{
              "width":1170,
              "height":433}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b76bda68bb174de1a882b66742982f86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":957},
                "size":{
                  "width":1170,
                  "height":433}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Project in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"project.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u63.jpg"}},
{
          "id":"64ff0388338443a6931dbc3144bccf57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":497},
            "size":{
              "width":1170,
              "height":433}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b1351481bbf47788a3d1ea458cc82f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":497},
                "size":{
                  "width":1170,
                  "height":433}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Project in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"project.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u63.jpg"}},
{
          "id":"37809c9900fd4efa9e7b83e3856ab673",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":249},
            "size":{
              "width":1174,
              "height":221}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"434a078a437a43209168442ad6fb22ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":249},
                "size":{
                  "width":1174,
                  "height":221}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u65.png"}},
{
          "id":"7b2572f4ff07489f95326afc77ff6732",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":270},
            "size":{
              "width":182,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11c9f645cd4d421dbe59efe3f8c89bc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":270},
                "size":{
                  "width":182,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u67.png"}},
{
          "id":"6e884c6b334c4385bf54cb12d0fac2b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":280},
            "size":{
              "width":163,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16a1386ff8c947f08a0dce9884777f06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":280},
                "size":{
                  "width":163,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u69.png"}},
{
          "id":"225f8c1cc4544d6d999ed1375a32e723",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":69,
              "y":417},
            "size":{
              "width":143,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bfd56bcf7eb4535ace4f1e37d353486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":69,
                  "y":417},
                "size":{
                  "width":143,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"218178f2b8064c84bf155e72228dfdd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":270},
            "size":{
              "width":182,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de1b711c2110423083557bb4ae767909",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":270},
                "size":{
                  "width":182,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u67.png"}},
{
          "id":"8c55cae48faa49bd89b80651bc1ceafa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":280},
            "size":{
              "width":163,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef5c7c63b40645b4b02a9fadf8f7435f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":280},
                "size":{
                  "width":163,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u69.png"}},
{
          "id":"d2b7987a8d8a423483a783fbf8477bb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":261,
              "y":417},
            "size":{
              "width":143,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5e3649cb1114fe6b8da97f2b4174282",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":261,
                  "y":417},
                "size":{
                  "width":143,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf52a429cf844982acb3df47e1047e89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":443,
              "y":270},
            "size":{
              "width":182,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91079bec55c84ae498c4ba125e6a43f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":443,
                  "y":270},
                "size":{
                  "width":182,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u67.png"}},
{
          "id":"a328ab1c03c6491a815e0f224b6f02ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":280},
            "size":{
              "width":163,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45053cb40ff540519d101ecee95a4fcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":280},
                "size":{
                  "width":163,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u69.png"}},
{
          "id":"ceca28982fcf4ffabcca6923fb7293c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":452,
              "y":417},
            "size":{
              "width":143,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0e99267856f4a039d49cf59aefa2378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":452,
                  "y":417},
                "size":{
                  "width":143,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7daf47224e3048c6b0e803ddd50146eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":635,
              "y":270},
            "size":{
              "width":182,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4696cb96c1a4dc18001898f5b7719bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":635,
                  "y":270},
                "size":{
                  "width":182,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u67.png"}},
{
          "id":"aabf99746852477fabe6b28d1c1cb130",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":644,
              "y":280},
            "size":{
              "width":163,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f3fa70b7a43403fa4080fd0778a9b6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":644,
                  "y":280},
                "size":{
                  "width":163,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u69.png"}},
{
          "id":"f83aa7c20a6c472897f4438e7e11ecc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":644,
              "y":417},
            "size":{
              "width":143,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c09913bd74f4fd9a0b92df08f9d140f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":644,
                  "y":417},
                "size":{
                  "width":143,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37c50c968d3f4c6ea868afbd654f9103",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":826,
              "y":270},
            "size":{
              "width":182,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ada7ede34c74c46819aff3f29b1f6d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":826,
                  "y":270},
                "size":{
                  "width":182,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u67.png"}},
{
          "id":"2f001ec5013c410d898438eb4880022a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":836,
              "y":280},
            "size":{
              "width":163,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ba6772bfd894006bdab600880cc0bb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":836,
                  "y":280},
                "size":{
                  "width":163,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u69.png"}},
{
          "id":"841d374f925b4601a0b645f2d42cb1f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":836,
              "y":417},
            "size":{
              "width":143,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9637fe70cb834b19b031f3eedd08f9e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":836,
                  "y":417},
                "size":{
                  "width":143,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4eebdf5f2deb4e71861fb144f5488db5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1018,
              "y":270},
            "size":{
              "width":182,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7522b869c44c4e8db67f410f291f854e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1018,
                  "y":270},
                "size":{
                  "width":182,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u67.png"}},
{
          "id":"e02e1c20673f46b195e1a859c2d0baf2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1027,
              "y":280},
            "size":{
              "width":163,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e3fed6776964fb6947047a2791d7d24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1027,
                  "y":280},
                "size":{
                  "width":163,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u69.png"}},
{
          "id":"e08310414b404d19a351f13b398659c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1027,
              "y":417},
            "size":{
              "width":143,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89bafe647dbf41aaabd018419e8ef981",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1027,
                  "y":417},
                "size":{
                  "width":143,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c72736cba4640b5ae5ebbca312c6169",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":957},
            "size":{
              "width":570,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff9a1abdc85143458e6fae1322d618a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":957},
                "size":{
                  "width":570,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/category/u103.png"}}]}},
  "masters":{
    "3c2651543160467bb6dbd1c6e4fb5ae6":{
      "packageId":"3c2651543160467bb6dbd1c6e4fb5ae6",
      "type":"Axure:Master",
      "name":"Хидер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a24d26dd8cbf4f848f51c061f19d3ec2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-30},
              "size":{
                "width":1280,
                "height":207}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad4a5933465143999cd6214d999692d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-30},
                  "size":{
                    "width":1280,
                    "height":207}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"1986c1faae294ce5b785ebea9c9954d1",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":109},
              "size":{
                "width":950,
                "height":68}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b476c7edf27f4f47a1e333f7f8061d5e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":950,
                    "height":68}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2008e102df584d74a483975847661c17",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"824e543911104969870ab12502c80eda",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"b51e264b43464b27af113cbf070b274d",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":190,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0e31ad92b7bc4eeb941d4fc5633165db",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":190,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Category in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"category.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"94faf73cf2a140e1b5a65136362028b0",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":380,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"24f6277a43d84fe58c2bcc94f1624738",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":380,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"41195ca2d4eb4b25b02f328962a88fea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":570,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"262376ede03e425c805a7ee916d5dc4d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":570,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"774d22def07f4b3b92beaf7d3113c8e3",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":760,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f3ade7596611440d93de5a3f4d363b75",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":760,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u17.png"}}]}]},
{
            "id":"0f0ce908cb5e4e668e2051a152a009ac",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":-28.5},
              "size":{
                "width":480,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a3eac7c066243798a5b2c6235b26a0e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":-28.5},
                  "size":{
                    "width":480,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"63bef173bd0141fc9010fbfe0fd9b35c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "location":{
                "x":1114,
                "y":56},
              "size":{
                "width":107,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"310aa94f3d31441c9e33bfd9c9646e91",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "location":{
                    "x":1114,
                    "y":56},
                  "size":{
                    "width":107,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"00fdbbc6f18a432fb754444bec683a49",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1207,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2d93413044cbfac754e65e456484a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1207,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u23.png"}},
{
            "id":"2b5505a026064198ae5312894c44877b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1165,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb4c16b29de94517bf081a61ec087285",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1165,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u25.png"}},
{
            "id":"1b1cbe0241714a378a81b178b0e86735",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1123,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c8fefe866140448f1e15b946398de4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1123,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fbe7887b2aad40989761f1b43212d52b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1081,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4cd45276529f4bfcb293119e311b3986",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1081,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"db9085386ae0403b872a52d3388be44d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":12,
                "y":8},
              "size":{
                "width":318,
                "height":57}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c72d5500e5974604a2afbae40f0bcab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":12,
                    "y":8},
                  "size":{
                    "width":318,
                    "height":57}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f6f939892ba64f94b76ad834e47d4b82",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":16,
                "y":64},
              "size":{
                "width":304,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"edfd1d481b144801bf684f564d0f14e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":16,
                    "y":64},
                  "size":{
                    "width":304,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb0d2181a3c346fda67248f2169af96c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":16,
                "y":-9},
              "size":{
                "width":108,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"01f1ed0e703140aaac8556b31d9fdc11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":-9},
                  "size":{
                    "width":108,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"885685ceb66b434e863ffd0845fa2b42",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1094,
                "y":54},
              "size":{
                "width":10,
                "height":32}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u37_line.png"}},
{
            "id":"82b50fcf1e0e409d9a5a12e93a7f8f67",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "location":{
                "x":980,
                "y":56},
              "size":{
                "width":104,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b12036b93c294313a4203a7ee8ea1f7c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "location":{
                    "x":980,
                    "y":56},
                  "size":{
                    "width":104,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open News in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "1c043ff96f1947a9b4613e78a73b6b0b":{
      "packageId":"1c043ff96f1947a9b4613e78a73b6b0b",
      "type":"Axure:Master",
      "name":"Футер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9fc91ae066174b309c3f0d46fe8888fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-10,
                "y":0},
              "size":{
                "width":1280,
                "height":300}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"66be155d52ee42588ea72dbc1f055f90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-10,
                    "y":0},
                  "size":{
                    "width":1280,
                    "height":300}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}},
{
            "id":"ddea022546f74b6fa41947b0291e2334",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":30,
                "y":14},
              "size":{
                "width":101,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89f2e4dfdcaf410fa5ba9dd499dc91b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":30,
                    "y":14},
                  "size":{
                    "width":101,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f5eb2795b014e089f2a0a4dcc667061",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":53},
              "size":{
                "width":70,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"763500db2a414e9e8c8b8a14e1d09b1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":53},
                  "size":{
                    "width":70,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b333f7fb5b88469b8dd4f8a599b79e6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":85},
              "size":{
                "width":68,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a84e81a6f8fd42b0a235a0ddca308e2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":85},
                  "size":{
                    "width":68,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"eda8c6e1c5184795bf3b637a1369fe9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":117},
              "size":{
                "width":64,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19eb2d053ee740da8b420086cb0ed542",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":117},
                  "size":{
                    "width":64,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bd067fad9b9d48deb6e6c41eb0492c8a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":332,
                "y":14},
              "size":{
                "width":111,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fcdd4cbfa904ec8aeac78a1a733ad40",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":332,
                    "y":14},
                  "size":{
                    "width":111,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce3bd7deeed248f89cf82ca82eeeed3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":332,
                "y":50},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92f32b9871b54ea6a20d2ecc7241d883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":332,
                    "y":50},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"11ad65cd45e84f4b95f147f21f1657c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":680,
                "y":14},
              "size":{
                "width":98,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93173ecf7ca04258870af0834f832b53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":680,
                    "y":14},
                  "size":{
                    "width":98,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e024c2b6a9384da7b6c1c8db894e3fd0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":50},
              "size":{
                "width":153,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80655206f5704739b7a76c9bd5754d26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":50},
                  "size":{
                    "width":153,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6d49b834c588458686a066d938e026be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":989,
                "y":14},
              "size":{
                "width":167,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe5fbb369ebb4ac8b1ee950406136e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":989,
                    "y":14},
                  "size":{
                    "width":167,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f663051151124546aa320df44882e86a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":989.000061035156,
                "y":50},
              "size":{
                "width":221,
                "height":220}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d76f835091e4469ea3d2706eb50c48ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":989.000061035156,
                    "y":50},
                  "size":{
                    "width":221,
                    "height":220}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u61.jpg"}}]}}},
  "objectPaths":{
    "573287fbecb241ffb2768c166453bcf5":{
      "scriptId":"u0",
      "a24d26dd8cbf4f848f51c061f19d3ec2":{
        "scriptId":"u1"},
      "ad4a5933465143999cd6214d999692d6":{
        "scriptId":"u2"},
      "1986c1faae294ce5b785ebea9c9954d1":{
        "scriptId":"u3"},
      "b476c7edf27f4f47a1e333f7f8061d5e":{
        "scriptId":"u4"},
      "2008e102df584d74a483975847661c17":{
        "scriptId":"u5"},
      "824e543911104969870ab12502c80eda":{
        "scriptId":"u6"},
      "b51e264b43464b27af113cbf070b274d":{
        "scriptId":"u7"},
      "0e31ad92b7bc4eeb941d4fc5633165db":{
        "scriptId":"u8"},
      "94faf73cf2a140e1b5a65136362028b0":{
        "scriptId":"u9"},
      "24f6277a43d84fe58c2bcc94f1624738":{
        "scriptId":"u10"},
      "41195ca2d4eb4b25b02f328962a88fea":{
        "scriptId":"u11"},
      "262376ede03e425c805a7ee916d5dc4d":{
        "scriptId":"u12"},
      "774d22def07f4b3b92beaf7d3113c8e3":{
        "scriptId":"u13"},
      "f3ade7596611440d93de5a3f4d363b75":{
        "scriptId":"u14"},
      "0f0ce908cb5e4e668e2051a152a009ac":{
        "scriptId":"u15"},
      "8a3eac7c066243798a5b2c6235b26a0e":{
        "scriptId":"u16"},
      "63bef173bd0141fc9010fbfe0fd9b35c":{
        "scriptId":"u17"},
      "310aa94f3d31441c9e33bfd9c9646e91":{
        "scriptId":"u18"},
      "00fdbbc6f18a432fb754444bec683a49":{
        "scriptId":"u19"},
      "cdf2d93413044cbfac754e65e456484a":{
        "scriptId":"u20"},
      "2b5505a026064198ae5312894c44877b":{
        "scriptId":"u21"},
      "bb4c16b29de94517bf081a61ec087285":{
        "scriptId":"u22"},
      "1b1cbe0241714a378a81b178b0e86735":{
        "scriptId":"u23"},
      "68c8fefe866140448f1e15b946398de4":{
        "scriptId":"u24"},
      "fbe7887b2aad40989761f1b43212d52b":{
        "scriptId":"u25"},
      "4cd45276529f4bfcb293119e311b3986":{
        "scriptId":"u26"},
      "db9085386ae0403b872a52d3388be44d":{
        "scriptId":"u27"},
      "c72d5500e5974604a2afbae40f0bcab2":{
        "scriptId":"u28"},
      "f6f939892ba64f94b76ad834e47d4b82":{
        "scriptId":"u29"},
      "edfd1d481b144801bf684f564d0f14e2":{
        "scriptId":"u30"},
      "bb0d2181a3c346fda67248f2169af96c":{
        "scriptId":"u31"},
      "01f1ed0e703140aaac8556b31d9fdc11":{
        "scriptId":"u32"},
      "885685ceb66b434e863ffd0845fa2b42":{
        "scriptId":"u33"},
      "82b50fcf1e0e409d9a5a12e93a7f8f67":{
        "scriptId":"u34"},
      "b12036b93c294313a4203a7ee8ea1f7c":{
        "scriptId":"u35"}},
    "10486424da8b47ebbbb349543a5017cb":{
      "scriptId":"u36",
      "9fc91ae066174b309c3f0d46fe8888fb":{
        "scriptId":"u37"},
      "66be155d52ee42588ea72dbc1f055f90":{
        "scriptId":"u38"},
      "ddea022546f74b6fa41947b0291e2334":{
        "scriptId":"u39"},
      "89f2e4dfdcaf410fa5ba9dd499dc91b8":{
        "scriptId":"u40"},
      "9f5eb2795b014e089f2a0a4dcc667061":{
        "scriptId":"u41"},
      "763500db2a414e9e8c8b8a14e1d09b1a":{
        "scriptId":"u42"},
      "b333f7fb5b88469b8dd4f8a599b79e6a":{
        "scriptId":"u43"},
      "a84e81a6f8fd42b0a235a0ddca308e2a":{
        "scriptId":"u44"},
      "eda8c6e1c5184795bf3b637a1369fe9d":{
        "scriptId":"u45"},
      "19eb2d053ee740da8b420086cb0ed542":{
        "scriptId":"u46"},
      "bd067fad9b9d48deb6e6c41eb0492c8a":{
        "scriptId":"u47"},
      "5fcdd4cbfa904ec8aeac78a1a733ad40":{
        "scriptId":"u48"},
      "ce3bd7deeed248f89cf82ca82eeeed3f":{
        "scriptId":"u49"},
      "92f32b9871b54ea6a20d2ecc7241d883":{
        "scriptId":"u50"},
      "11ad65cd45e84f4b95f147f21f1657c2":{
        "scriptId":"u51"},
      "93173ecf7ca04258870af0834f832b53":{
        "scriptId":"u52"},
      "e024c2b6a9384da7b6c1c8db894e3fd0":{
        "scriptId":"u53"},
      "80655206f5704739b7a76c9bd5754d26":{
        "scriptId":"u54"},
      "6d49b834c588458686a066d938e026be":{
        "scriptId":"u55"},
      "fe5fbb369ebb4ac8b1ee950406136e69":{
        "scriptId":"u56"},
      "f663051151124546aa320df44882e86a":{
        "scriptId":"u57"},
      "d76f835091e4469ea3d2706eb50c48ae":{
        "scriptId":"u58"}},
    "6326b92ef65a4232a35c096e1bb1f130":{
      "scriptId":"u59"},
    "9b706e56b5f34570b89dedb2926e23ed":{
      "scriptId":"u60"},
    "5ac7992d08374ac8b47fa25d4aa8a962":{
      "scriptId":"u61"},
    "b76bda68bb174de1a882b66742982f86":{
      "scriptId":"u62"},
    "64ff0388338443a6931dbc3144bccf57":{
      "scriptId":"u63"},
    "8b1351481bbf47788a3d1ea458cc82f6":{
      "scriptId":"u64"},
    "37809c9900fd4efa9e7b83e3856ab673":{
      "scriptId":"u65"},
    "434a078a437a43209168442ad6fb22ee":{
      "scriptId":"u66"},
    "7b2572f4ff07489f95326afc77ff6732":{
      "scriptId":"u67"},
    "11c9f645cd4d421dbe59efe3f8c89bc9":{
      "scriptId":"u68"},
    "6e884c6b334c4385bf54cb12d0fac2b1":{
      "scriptId":"u69"},
    "16a1386ff8c947f08a0dce9884777f06":{
      "scriptId":"u70"},
    "225f8c1cc4544d6d999ed1375a32e723":{
      "scriptId":"u71"},
    "5bfd56bcf7eb4535ace4f1e37d353486":{
      "scriptId":"u72"},
    "218178f2b8064c84bf155e72228dfdd8":{
      "scriptId":"u73"},
    "de1b711c2110423083557bb4ae767909":{
      "scriptId":"u74"},
    "8c55cae48faa49bd89b80651bc1ceafa":{
      "scriptId":"u75"},
    "ef5c7c63b40645b4b02a9fadf8f7435f":{
      "scriptId":"u76"},
    "d2b7987a8d8a423483a783fbf8477bb9":{
      "scriptId":"u77"},
    "b5e3649cb1114fe6b8da97f2b4174282":{
      "scriptId":"u78"},
    "bf52a429cf844982acb3df47e1047e89":{
      "scriptId":"u79"},
    "91079bec55c84ae498c4ba125e6a43f0":{
      "scriptId":"u80"},
    "a328ab1c03c6491a815e0f224b6f02ff":{
      "scriptId":"u81"},
    "45053cb40ff540519d101ecee95a4fcf":{
      "scriptId":"u82"},
    "ceca28982fcf4ffabcca6923fb7293c0":{
      "scriptId":"u83"},
    "d0e99267856f4a039d49cf59aefa2378":{
      "scriptId":"u84"},
    "7daf47224e3048c6b0e803ddd50146eb":{
      "scriptId":"u85"},
    "d4696cb96c1a4dc18001898f5b7719bf":{
      "scriptId":"u86"},
    "aabf99746852477fabe6b28d1c1cb130":{
      "scriptId":"u87"},
    "5f3fa70b7a43403fa4080fd0778a9b6e":{
      "scriptId":"u88"},
    "f83aa7c20a6c472897f4438e7e11ecc6":{
      "scriptId":"u89"},
    "6c09913bd74f4fd9a0b92df08f9d140f":{
      "scriptId":"u90"},
    "37c50c968d3f4c6ea868afbd654f9103":{
      "scriptId":"u91"},
    "9ada7ede34c74c46819aff3f29b1f6d5":{
      "scriptId":"u92"},
    "2f001ec5013c410d898438eb4880022a":{
      "scriptId":"u93"},
    "7ba6772bfd894006bdab600880cc0bb1":{
      "scriptId":"u94"},
    "841d374f925b4601a0b645f2d42cb1f4":{
      "scriptId":"u95"},
    "9637fe70cb834b19b031f3eedd08f9e8":{
      "scriptId":"u96"},
    "4eebdf5f2deb4e71861fb144f5488db5":{
      "scriptId":"u97"},
    "7522b869c44c4e8db67f410f291f854e":{
      "scriptId":"u98"},
    "e02e1c20673f46b195e1a859c2d0baf2":{
      "scriptId":"u99"},
    "2e3fed6776964fb6947047a2791d7d24":{
      "scriptId":"u100"},
    "e08310414b404d19a351f13b398659c5":{
      "scriptId":"u101"},
    "89bafe647dbf41aaabd018419e8ef981":{
      "scriptId":"u102"},
    "6c72736cba4640b5ae5ebbca312c6169":{
      "scriptId":"u103"},
    "ff9a1abdc85143458e6fae1322d618a6":{
      "scriptId":"u104"}}});