$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1423593362066.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8f5dfa0f81084b979632a1f594ad9144",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6b9efb948dc14420a1374b04f535c06e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":10,
              "y":228},
            "size":{
              "width":1280,
              "height":1462}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d1807f1f053464a88f9d80da74002f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":10,
                  "y":228},
                "size":{
                  "width":1280,
                  "height":1462}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"75114f23744f467ca97d59884d8eb3ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":260},
            "size":{
              "width":1172,
              "height":510},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3b83adea2fa44668b89d9eeea9232b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":260},
                "size":{
                  "width":1172,
                  "height":510},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"da0d93c42c0f4b10b54725537938570a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":11}},
          "adaptiveStyles":{
},
          "masterId":"3c2651543160467bb6dbd1c6e4fb5ae6"},
{
          "id":"ef975174554e4f3686d5473a0acab993",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1710}},
          "adaptiveStyles":{
},
          "masterId":"1c043ff96f1947a9b4613e78a73b6b0b"},
{
          "id":"20b07032aa014d9d9e97f0428fe9a9aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":1251},
            "size":{
              "width":1170,
              "height":433}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eda8ded6200d40fca55d78c316641add",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":1251},
                "size":{
                  "width":1170,
                  "height":433}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Project in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"project.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u63.jpg"}},
{
          "id":"925a98836c5141e2a7416e41d5b01521",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":790},
            "size":{
              "width":1170,
              "height":433}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aea2fe4579c482694adf9a786695d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":790},
                "size":{
                  "width":1170,
                  "height":433}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Project in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"project.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u63.jpg"}},
{
          "id":"a63ea75e410e4032bb139efdf453af91",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":330},
            "size":{
              "width":1163,
              "height":433}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae648d07cc2c405e98c8084330e22812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":330},
                "size":{
                  "width":1163,
                  "height":433}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Project in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"project.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u63.jpg"}},
{
          "id":"603fd6d139f9459dac65398db0ca3d82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":70,
              "y":276},
            "size":{
              "width":385,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"444d801e1d4248f68ba8fb6e5711fd74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":276},
                "size":{
                  "width":385,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "3c2651543160467bb6dbd1c6e4fb5ae6":{
      "packageId":"3c2651543160467bb6dbd1c6e4fb5ae6",
      "type":"Axure:Master",
      "name":"Хидер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a24d26dd8cbf4f848f51c061f19d3ec2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":-30},
              "size":{
                "width":1280,
                "height":207}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad4a5933465143999cd6214d999692d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-1,
                    "y":-30},
                  "size":{
                    "width":1280,
                    "height":207}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"1986c1faae294ce5b785ebea9c9954d1",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":-1,
                "y":109},
              "size":{
                "width":950,
                "height":68}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b476c7edf27f4f47a1e333f7f8061d5e",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":950,
                    "height":68}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2008e102df584d74a483975847661c17",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"824e543911104969870ab12502c80eda",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"b51e264b43464b27af113cbf070b274d",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":190,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0e31ad92b7bc4eeb941d4fc5633165db",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":190,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Category in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"category.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"94faf73cf2a140e1b5a65136362028b0",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":380,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"24f6277a43d84fe58c2bcc94f1624738",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":380,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"41195ca2d4eb4b25b02f328962a88fea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":570,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"262376ede03e425c805a7ee916d5dc4d",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":570,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"774d22def07f4b3b92beaf7d3113c8e3",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":760,
                        "y":0},
                      "size":{
                        "width":190,
                        "height":68}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f3ade7596611440d93de5a3f4d363b75",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":760,
                            "y":0},
                          "size":{
                            "width":190,
                            "height":68}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u17.png"}}]}]},
{
            "id":"0f0ce908cb5e4e668e2051a152a009ac",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":-28.5},
              "size":{
                "width":480,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a3eac7c066243798a5b2c6235b26a0e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":-28.5},
                  "size":{
                    "width":480,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"63bef173bd0141fc9010fbfe0fd9b35c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "location":{
                "x":1114,
                "y":56},
              "size":{
                "width":107,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"310aa94f3d31441c9e33bfd9c9646e91",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "location":{
                    "x":1114,
                    "y":56},
                  "size":{
                    "width":107,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"00fdbbc6f18a432fb754444bec683a49",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1207,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cdf2d93413044cbfac754e65e456484a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1207,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u23.png"}},
{
            "id":"2b5505a026064198ae5312894c44877b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1165,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb4c16b29de94517bf081a61ec087285",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1165,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u25.png"}},
{
            "id":"1b1cbe0241714a378a81b178b0e86735",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1123,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c8fefe866140448f1e15b946398de4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1123,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"fbe7887b2aad40989761f1b43212d52b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1081,
                "y":-9},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4cd45276529f4bfcb293119e311b3986",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1081,
                    "y":-9},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u29.png"}},
{
            "id":"db9085386ae0403b872a52d3388be44d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":12,
                "y":8},
              "size":{
                "width":318,
                "height":57}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c72d5500e5974604a2afbae40f0bcab2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":12,
                    "y":8},
                  "size":{
                    "width":318,
                    "height":57}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f6f939892ba64f94b76ad834e47d4b82",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "location":{
                "x":16,
                "y":64},
              "size":{
                "width":304,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"edfd1d481b144801bf684f564d0f14e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "location":{
                    "x":16,
                    "y":64},
                  "size":{
                    "width":304,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb0d2181a3c346fda67248f2169af96c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":16,
                "y":-9},
              "size":{
                "width":108,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"01f1ed0e703140aaac8556b31d9fdc11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":-9},
                  "size":{
                    "width":108,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"885685ceb66b434e863ffd0845fa2b42",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1094,
                "y":54},
              "size":{
                "width":10,
                "height":32}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u37_line.png"}},
{
            "id":"82b50fcf1e0e409d9a5a12e93a7f8f67",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Обычный', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "location":{
                "x":980,
                "y":56},
              "size":{
                "width":104,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b12036b93c294313a4203a7ee8ea1f7c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Обычный', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "location":{
                    "x":980,
                    "y":56},
                  "size":{
                    "width":104,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open News in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"news.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "1c043ff96f1947a9b4613e78a73b6b0b":{
      "packageId":"1c043ff96f1947a9b4613e78a73b6b0b",
      "type":"Axure:Master",
      "name":"Футер",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9fc91ae066174b309c3f0d46fe8888fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":-10,
                "y":0},
              "size":{
                "width":1280,
                "height":300}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"66be155d52ee42588ea72dbc1f055f90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-10,
                    "y":0},
                  "size":{
                    "width":1280,
                    "height":300}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u41.png"}},
{
            "id":"ddea022546f74b6fa41947b0291e2334",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":30,
                "y":14},
              "size":{
                "width":101,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89f2e4dfdcaf410fa5ba9dd499dc91b8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":30,
                    "y":14},
                  "size":{
                    "width":101,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f5eb2795b014e089f2a0a4dcc667061",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":53},
              "size":{
                "width":70,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"763500db2a414e9e8c8b8a14e1d09b1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":53},
                  "size":{
                    "width":70,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b333f7fb5b88469b8dd4f8a599b79e6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":85},
              "size":{
                "width":68,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a84e81a6f8fd42b0a235a0ddca308e2a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":85},
                  "size":{
                    "width":68,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"eda8c6e1c5184795bf3b637a1369fe9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":30,
                "y":117},
              "size":{
                "width":64,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19eb2d053ee740da8b420086cb0ed542",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":30,
                    "y":117},
                  "size":{
                    "width":64,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bd067fad9b9d48deb6e6c41eb0492c8a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":332,
                "y":14},
              "size":{
                "width":111,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fcdd4cbfa904ec8aeac78a1a733ad40",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":332,
                    "y":14},
                  "size":{
                    "width":111,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce3bd7deeed248f89cf82ca82eeeed3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":332,
                "y":50},
              "size":{
                "width":148,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92f32b9871b54ea6a20d2ecc7241d883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":332,
                    "y":50},
                  "size":{
                    "width":148,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"11ad65cd45e84f4b95f147f21f1657c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":680,
                "y":14},
              "size":{
                "width":98,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93173ecf7ca04258870af0834f832b53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":680,
                    "y":14},
                  "size":{
                    "width":98,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e024c2b6a9384da7b6c1c8db894e3fd0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":50},
              "size":{
                "width":153,
                "height":64}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80655206f5704739b7a76c9bd5754d26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":50},
                  "size":{
                    "width":153,
                    "height":64}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6d49b834c588458686a066d938e026be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Полужирный', 'Arial'",
              "fontSize":"22px",
              "fontWeight":"700",
              "location":{
                "x":989,
                "y":14},
              "size":{
                "width":167,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe5fbb369ebb4ac8b1ee950406136e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Полужирный', 'Arial'",
                  "fontSize":"22px",
                  "fontWeight":"700",
                  "location":{
                    "x":989,
                    "y":14},
                  "size":{
                    "width":167,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f663051151124546aa320df44882e86a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":989.000061035156,
                "y":50},
              "size":{
                "width":221,
                "height":220}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d76f835091e4469ea3d2706eb50c48ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":989.000061035156,
                    "y":50},
                  "size":{
                    "width":221,
                    "height":220}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u61.jpg"}}]}}},
  "objectPaths":{
    "6b9efb948dc14420a1374b04f535c06e":{
      "scriptId":"u0"},
    "7d1807f1f053464a88f9d80da74002f4":{
      "scriptId":"u1"},
    "75114f23744f467ca97d59884d8eb3ba":{
      "scriptId":"u2"},
    "d3b83adea2fa44668b89d9eeea9232b4":{
      "scriptId":"u3"},
    "da0d93c42c0f4b10b54725537938570a":{
      "scriptId":"u4",
      "a24d26dd8cbf4f848f51c061f19d3ec2":{
        "scriptId":"u5"},
      "ad4a5933465143999cd6214d999692d6":{
        "scriptId":"u6"},
      "1986c1faae294ce5b785ebea9c9954d1":{
        "scriptId":"u7"},
      "b476c7edf27f4f47a1e333f7f8061d5e":{
        "scriptId":"u8"},
      "2008e102df584d74a483975847661c17":{
        "scriptId":"u9"},
      "824e543911104969870ab12502c80eda":{
        "scriptId":"u10"},
      "b51e264b43464b27af113cbf070b274d":{
        "scriptId":"u11"},
      "0e31ad92b7bc4eeb941d4fc5633165db":{
        "scriptId":"u12"},
      "94faf73cf2a140e1b5a65136362028b0":{
        "scriptId":"u13"},
      "24f6277a43d84fe58c2bcc94f1624738":{
        "scriptId":"u14"},
      "41195ca2d4eb4b25b02f328962a88fea":{
        "scriptId":"u15"},
      "262376ede03e425c805a7ee916d5dc4d":{
        "scriptId":"u16"},
      "774d22def07f4b3b92beaf7d3113c8e3":{
        "scriptId":"u17"},
      "f3ade7596611440d93de5a3f4d363b75":{
        "scriptId":"u18"},
      "0f0ce908cb5e4e668e2051a152a009ac":{
        "scriptId":"u19"},
      "8a3eac7c066243798a5b2c6235b26a0e":{
        "scriptId":"u20"},
      "63bef173bd0141fc9010fbfe0fd9b35c":{
        "scriptId":"u21"},
      "310aa94f3d31441c9e33bfd9c9646e91":{
        "scriptId":"u22"},
      "00fdbbc6f18a432fb754444bec683a49":{
        "scriptId":"u23"},
      "cdf2d93413044cbfac754e65e456484a":{
        "scriptId":"u24"},
      "2b5505a026064198ae5312894c44877b":{
        "scriptId":"u25"},
      "bb4c16b29de94517bf081a61ec087285":{
        "scriptId":"u26"},
      "1b1cbe0241714a378a81b178b0e86735":{
        "scriptId":"u27"},
      "68c8fefe866140448f1e15b946398de4":{
        "scriptId":"u28"},
      "fbe7887b2aad40989761f1b43212d52b":{
        "scriptId":"u29"},
      "4cd45276529f4bfcb293119e311b3986":{
        "scriptId":"u30"},
      "db9085386ae0403b872a52d3388be44d":{
        "scriptId":"u31"},
      "c72d5500e5974604a2afbae40f0bcab2":{
        "scriptId":"u32"},
      "f6f939892ba64f94b76ad834e47d4b82":{
        "scriptId":"u33"},
      "edfd1d481b144801bf684f564d0f14e2":{
        "scriptId":"u34"},
      "bb0d2181a3c346fda67248f2169af96c":{
        "scriptId":"u35"},
      "01f1ed0e703140aaac8556b31d9fdc11":{
        "scriptId":"u36"},
      "885685ceb66b434e863ffd0845fa2b42":{
        "scriptId":"u37"},
      "82b50fcf1e0e409d9a5a12e93a7f8f67":{
        "scriptId":"u38"},
      "b12036b93c294313a4203a7ee8ea1f7c":{
        "scriptId":"u39"}},
    "ef975174554e4f3686d5473a0acab993":{
      "scriptId":"u40",
      "9fc91ae066174b309c3f0d46fe8888fb":{
        "scriptId":"u41"},
      "66be155d52ee42588ea72dbc1f055f90":{
        "scriptId":"u42"},
      "ddea022546f74b6fa41947b0291e2334":{
        "scriptId":"u43"},
      "89f2e4dfdcaf410fa5ba9dd499dc91b8":{
        "scriptId":"u44"},
      "9f5eb2795b014e089f2a0a4dcc667061":{
        "scriptId":"u45"},
      "763500db2a414e9e8c8b8a14e1d09b1a":{
        "scriptId":"u46"},
      "b333f7fb5b88469b8dd4f8a599b79e6a":{
        "scriptId":"u47"},
      "a84e81a6f8fd42b0a235a0ddca308e2a":{
        "scriptId":"u48"},
      "eda8c6e1c5184795bf3b637a1369fe9d":{
        "scriptId":"u49"},
      "19eb2d053ee740da8b420086cb0ed542":{
        "scriptId":"u50"},
      "bd067fad9b9d48deb6e6c41eb0492c8a":{
        "scriptId":"u51"},
      "5fcdd4cbfa904ec8aeac78a1a733ad40":{
        "scriptId":"u52"},
      "ce3bd7deeed248f89cf82ca82eeeed3f":{
        "scriptId":"u53"},
      "92f32b9871b54ea6a20d2ecc7241d883":{
        "scriptId":"u54"},
      "11ad65cd45e84f4b95f147f21f1657c2":{
        "scriptId":"u55"},
      "93173ecf7ca04258870af0834f832b53":{
        "scriptId":"u56"},
      "e024c2b6a9384da7b6c1c8db894e3fd0":{
        "scriptId":"u57"},
      "80655206f5704739b7a76c9bd5754d26":{
        "scriptId":"u58"},
      "6d49b834c588458686a066d938e026be":{
        "scriptId":"u59"},
      "fe5fbb369ebb4ac8b1ee950406136e69":{
        "scriptId":"u60"},
      "f663051151124546aa320df44882e86a":{
        "scriptId":"u61"},
      "d76f835091e4469ea3d2706eb50c48ae":{
        "scriptId":"u62"}},
    "20b07032aa014d9d9e97f0428fe9a9aa":{
      "scriptId":"u63"},
    "eda8ded6200d40fca55d78c316641add":{
      "scriptId":"u64"},
    "925a98836c5141e2a7416e41d5b01521":{
      "scriptId":"u65"},
    "5aea2fe4579c482694adf9a786695d48":{
      "scriptId":"u66"},
    "a63ea75e410e4032bb139efdf453af91":{
      "scriptId":"u67"},
    "ae648d07cc2c405e98c8084330e22812":{
      "scriptId":"u68"},
    "603fd6d139f9459dac65398db0ca3d82":{
      "scriptId":"u69"},
    "444d801e1d4248f68ba8fb6e5711fd74":{
      "scriptId":"u70"}}});